interface Proyecto {
    id: number;
    numero_proyecto: string;
    anio_proyecto: string;
    titulo_proyecto: string;
    tipo_proyecto: string;
    autor: string[];
    colaboradores: string | null;
    girado_a: string;
    acta_fecha: string;
    aprobado: boolean;
    tipo_norma: string;
    numero_norma: string | null;
    observaciones: string;
}

function parsearProyectos(texto: string): Proyecto[] {
    const lineas = texto.split('\n');
    const proyectos: Proyecto[] = [];
    let id = 5274;

    for (const linea of lineas) {
        if (!linea.trim()) continue;
        
        // Extraer número de proyecto
        const matchNumero = linea.match(/^(\d+)\.-/);
        if (!matchNumero) continue;
        const numeroProyecto = matchNumero[1];
        
        // Extraer año del proyecto (últimos 2 dígitos del número completo)
        const anioMatch = linea.match(/(\d+)\/(\d+)/);
        const anioProyecto = anioMatch ? `20${anioMatch[2]}` : "2024";
        
        // Extraer tipo de proyecto
        const tipoMatch = linea.match(/Proyecto de (ordenanza|declaración|comunicación|resolución)/i);
        const tipoProyecto = tipoMatch ? tipoMatch[1].toLowerCase() : "desconocido";
        
        // Extraer título
        const tituloMatch = linea.match(/:(.*?)\.\s*Autor/i) || linea.match(/- (.*?)\.\s*Autor/i);
        let tituloProyecto = tituloMatch ? tituloMatch[1].trim() : linea.split('. ')[0].split(':')[1]?.trim() || "";
        
        // Limpiar comillas del título si existen
        tituloProyecto = tituloProyecto.replace(/^“|”$|^"|"$/g, '');
        
        // Extraer autores
        const autorMatch = linea.match(/Autor(?:es)?: (.*?)(?=\.\s*(Iniciativa|Colaborador|Se gira|Sobre tablas|$))/i);
        const autor = autorMatch ? [autorMatch[1].trim()] : ["Intendente Municipal"];
        
        // Extraer colaboradores
        const colaboradorMatch = linea.match(/Colaborador(?:es)?: (.*?)(?=\.\s*(Se gira|Sobre tablas|Acta|$))/i);
        const colaboradores = colaboradorMatch ? colaboradorMatch[1].trim() : null;
        
        // Extraer girado a comisiones
        const giradoMatch = linea.match(/Se gira a (.*?)(?=\.\s*(Prioridad|Sobre tablas|Acta|$))/i);
        const girado_a = giradoMatch ? giradoMatch[1].trim() : "";
        
        // Extraer acta y fecha
        const actaMatch = linea.match(/Acta (\d+\/\d+)/);
        const acta_fecha = actaMatch ? actaMatch[1] : "";
        
        // Determinar estado de aprobación
        const aprobado = !linea.includes("Rechazado") && !linea.includes("Retirado") && !linea.includes("Vetado");
        
        // Extraer número de norma
        const normaMatch = linea.match(/([ODCR])-(\d+)-(\d+)/);
        let numero_norma = normaMatch ? normaMatch[0] : null;
        const tipo_norma = numero_norma 
            ? normaMatch![1] === 'O' ? 'ordenanza' 
              : normaMatch![1] === 'D' ? 'declaración'
              : normaMatch![1] === 'C' ? 'comunicación'
              : 'resolución'
            : tipoProyecto;
        
        // Extraer observaciones
        const observaciones = linea.includes("Sobre tablas") ? "Sobre tablas" : 
                             linea.match(/Prioridad de dictamen \((.*?)\)/)?.[1] || 
                             linea.match(/Tratamiento en conjunto \((.*?)\)/)?.[1] || 
                             "";

        proyectos.push({
            id: id++,
            numero_proyecto: numeroProyecto,
            anio_proyecto: anioProyecto,
            titulo_proyecto: tituloProyecto,
            tipo_proyecto: tipoProyecto,
            autor: autor,
            colaboradores: colaboradores,
            girado_a: girado_a,
            acta_fecha: acta_fecha,
            aprobado: aprobado,
            tipo_norma: tipo_norma,
            numero_norma: numero_norma,
            observaciones: observaciones
        });
    }

    return proyectos;
}

// Texto de entrada (aquí iría el contenido completo del archivo)
const proyectosTexto = `67.- Proyecto de ordenanza 67/24: “Modifica anexo I ordenanza 1747-CM-07. Se asigna, amplía denominación de calles barrio Coirones”. Autores: Concejales Natalia Almonacid, Silvio Barriga y Juan Pablo Ferrari (JSRN). Iniciativa: Cooperativa de Vivienda y Servicios Barrio Coirones y Colinas del Este LTDA. Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales. Prioridad de dictamen (legislativa del 03-07-24. Acta 16/24) O-25-3489 Acta 1201/25 del 20/03/25
68.- Proyecto de declaración 68/24: “Se declara interés municipal Rally Premio Aniversario Ciudad San Carlos de Bariloche 2024”. Autor: Concejal Tomás Hercigonja (PUL). Iniciativa: subsecretario de Deportes, Daniel Ljungberg. Sobre tablas. D-24-2986 Acta 1188/24 del 18/04/24.
69.- Proyecto de ordenanza 69/24: “Se modifica ordenanza 1862-CM-08 SIMBOV”. Autoras: Concejales Samanta Echenique (JXC) y Natalia Almonacid (JSRN). Colaboradora: Rocío Azkue. Sobre tablas. O-24-3450 Acta 1188/24 del 18/04/24.
70.- Proyecto de declaración 70/24: “Se declara de interés municipal al 4º Campeonato Regional Sur Maxibasquet Femenino”. Autores: Concejales María del Carmen Coronado, Gerardo Del Río y Tomás Hercigonja (PUL). Iniciativa: Asociación Civil Rionegrina de Maxibasquet Femenino. Sobre tablas. D-24-2987 Acta 1188/24 del 18/04/24.
71.- Proyecto de declaración 71/24: “Se declara de interés municipal y comunitario evento Nuevos Imaginarios del Sur”. Autora: Concejala Roxana Ferreyra (Nos Une). Iniciativa: Subsecretaría de Cultura, grupo de teatro mapuche El Katango, compañía La Patriótico Interesante, Universidad Nacional de Río Negro y Universidad Nacional de Concepción. Sobre tablas. D-24-2988 Acta 1188/24 del 18/04/24.
72.- Proyecto de comunicación 72/24: “Se comunica preocupación por falta de presupuesto de Universidades en Bariloche”. Autores: Concejales Julieta Wallace, Leandro Costa Brutten (IB), Gerardo Del Río, Maria Coronado, Tomas Hercigonja (PUL), Natalia Almonacid, Juan Pablo Ferrari y Silvio Barriga (JSRN), Roxana Ferreyra (Nos Une), Samanta Echenique (JxC) y Facundo Villalba (Primero Rio Negro).  C-24-1121 Acta 1188/24 del 18/04/24.
73.- Proyecto de declaración 73/24: “Se declara de interés municipal y comunitario proyecto “Teatro Público Independiente” Autora: Concejala Roxana Ferreyra (Nos Une). Iniciativa: Asociación de Teatrantes Bariloche. Sobre tablas. D-24-2992 Acta 1189/24 del 10/05/24.
74.- Proyecto de declaración 74/24: “Se declara de interés municipal y comunitario certificación internacional perros de búsqueda AUI”. Autora: Concejala Roxana Ferreyra (Nos Une). Iniciativa: Comisión de auxilio del Club Andino Bariloche (CAX). Sobre tablas. D-24-2993 Acta 1189/24 del 10/05/24.
75.- Proyecto de comunicación 75/24: “ Se comunica el rechazo y enérgico repudio al cierre de Télam”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre tablas. C-24-1122 Acta 1189/24 del 10/05/24.
76.- Proyecto de ordenanza 76/24: “Se presta acuerdo llamado licitación contratación agencia integral de marketing y medios. Emprotur”. Autores: Concejales Juan Pablo Ferrari (JSRN) y Facundo Villalba (Primero Río Negro). Iniciativa: Directorio del Emprotur. Sobre tablas. O-24-3452 Acta 1189/24 del 10/05/24.
77.- Proyecto de comunicación 77/24: “Se comunica la necesidad de darle continuidad al trabajo del INTI en Bariloche”. Autora: Concejala Julieta Wallace (Incluyendo Bariloche). Sobre tablas. C-24-1123 Acta 1189/24 del 10/05/24.
78.- Proyecto de ordenanza 78/24: “Se modifica ordenanza 2375-CM-12. Tarifas Estacionamiento Medido” Autora: Concejala Julieta Wallace (Incluyendo Bariloche). Iniciativa: Mesa de Cooperativas operadoras del SEMS (Kata Wain Nehuen, Ebenezer, Liwen, Nuevos Caminos y Encuentro). Se gira a Asesoría Letrada y a las comisiones de Economía, Hacienda, Finanzas, Desarrollo Económico y de Gobierno y Legales.   (Tratamiento en conjunto Economía y Gobierno. Acta 23 Leg. del 18/09/24) O-24-3468  Acta 1194/24 del 3/10/24.(subsumido con el proyecto 55/24) 
79.- Proyecto de comunicación 79/24: “Se comunica el repudio al vaciamiento del programa nacional Primeros Años”. Autores: Concejales Leandro Costa Brutten y Julieta Wallace (Incluyendo Bariloche). Colaborador: Concejo Deliberante de la Ciudad de General Roca. Sobre tablas. C-24-1124 Acta 1189/24 del 10/05/24.
80.- Proyecto de ordenanza 80/24: “Modifica artículo 4º inciso a) ordenanza 2017-CM-10”. Autor: Concejal Facundo Blanco Villalba (Primero Río Negro). Sobre tablas. O-24-3453 Acta 1189/24 del 10/05/24.
81.- Proyecto de ordenanza 81/24: “Regula bocas de expendio de alcohol. Modifica ordenanza 2548-CM-14” Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Colaborador: Juan Ramírez. Se gira a Asesoría Letrada y a las comisiones de Desarrollo Humano, Deportes y Cultura y de Gobierno y Legales. O-24-3475 Acta 1197/24 del 19/12/24.
82.- Proyecto de ordenanza 82/24: “Se declara área intangible a plazas, plazoletas y espacios verdes”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Iniciativa: Vecinos y Vecinas autoconvocados del km 13 de la Av. Exequiel Bustillo. Se gira a Asesoría Letrada y a las comisiones de Turismo y Medio Ambiente y de Gobierno y Legales.
83.- Proyecto de ordenanza 83/24: “Acepta renuncia. Integración Junta Electoral Municipal período 2024/2027”. Autores: Concejales Natalia Almonacid, Juan Pablo Ferrari, Laura Totonelli (JSRN), Gerardo Del Rio, Maria Coronado (PUL), Facundo Blanco Villalba (Primero Rio Negro) y Samanta Echenique (JxC). Sobre tablas. O-24-3451 Acta 1189 del 10/05/24.
84.- Proyecto de ordenanza 84/24: “Se crea programa de visualización de artistas con discapacidad como trabajadores, hacedores y espectadores”. Autora: Concejala Roxana Ferreyra (Nos Une). Iniciativa: Taller de ciudadanía CRE-ARTE. Se gira a Asesoría Letrada y a las comisiones de Desarrollo Humano, Deportes y Cultura y de Gobierno y Legales. O-24-3476 Acta 1197/24 del 19/12/24.
85.- Proyecto de comunicación 85/24: “Se comunica repudio a los hechos de violencia en espectáculos deportivos”. Autores: Concejales Leandro Costa Brutten (Incluyendo Bariloche); Facundo Blanco Villalba (Primero Río Negro) y Juan Pablo Ferrari (JSRN). Colaboradores: Liga de Fútbol Bariloche. C-24-1126 Acta 1189 del 10/05/24.
86.- Proyecto de comunicación 86/24: “Se comunica preocupación por caída de servicio eléctrico en la ciudad durante las nevadas” Autor: Concejal Juan Pablo Ferrari (JSRN). Sobre tabla. C-24-1125 Acta 1189/24 del 10/05/24.

87.- Proyecto de declaración 87/24: “Declara interés municipal The Distinguished Gentleman’s Ride ciudad San Carlos de Bariloche 2024”. Autor: Concejal Tomás Hercigonja (PUL). Iniciativa: Miguel Andino y Karina M. Bernard. Se solicitará su retiro por haberse emitido la resolución 124-PCM-24. D-24-3001 Acta 1190/24 del 30/05/24.

88.- Proyecto de ordenanza 88/24: “Aceptación de donación artículos deportivos y elementos de seguridad para la Subsecretaría de Deportes”. Autor: Intendente Municipal Walter Cortés. Colaborador: Secretario de Turismo, Sergio Herrero. Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales con tratamiento de Preferencia en 1° Sesión y prioridad de dictamen. (Acta 13/24 comisión Legislativa). Se retira la preferencia en 1° Sesión Acta 1191/24 del 04/07/24.

89.- Proyecto de comunicación 89/24: “Se comunica necesidad de mantener vigencia de emisoras rionegrinas de Radio Nacional”. Autora: Concejala Roxana Ferreyra (Nos Une). Sobre tablas. C-24-1127/24 Acta 1190 del 30/05/24.

90.- Proyecto de ordenanza 90/24: “Ratificar poder concedente del servicio de distribución de energía eléctrica”. Autora: Concejala Julieta Wallace (Incluyendo Bariloche). Se gira a Asesoría Letrada y a las comisiones de Servicios Tránsito y Transporte y Gobierno y Legales. Rechazado Acta 1195/24 del 31/10/24.

91.- Proyecto de declaración 91/24: “Se declara interés municipal e intercultural novena carrera continental de Jornada Paz y Dignidad”. Autora: Concejala Julieta Wallace (Incluyendo Bariloche). Iniciativa: Cristina Marín (Comunidad Lof Lafkenche). Sobre tablas. D-24-2997 Acta 1190/24 del 30/05/24.

92.- Proyecto de comunicación 92/24: “Emergencia tarifaria de servicios en el Municipio de San Carlos de Bariloche” Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Iniciativa: Multisectorial Federal de la República Argentina. Sobre tablas. C-24-1129 Acta 1190/24 del 30/05/24.

93.- Proyecto de comunicación 93/24: “Se comunica necesidad de la continuidad de Radio Nacional Pública”. Autora: Concejala Julieta Wallace (Incluyendo Bariloche).Sobre tablas. C-24-1128 Acta 1190/24 del 30/05/24.

94.- Proyecto de ordenanza 94/24: “Modifica ordenanza 1629-CM-12 regulación de tarifas del servicio de automóviles de alquiler con taxímetros”. Autor: Intendente Municipal, Walter Cortés. Colaborador: Secretario de Capital Humano, Acción Social y Deporte, Hector Fabian Zuniga.  Se gira a Asesoría Letrada y a las comisiones de Servicios, Tránsito y Transporte, de  Economía, Hacienda, Finanzas y Desarrollo Económico y de Gobierno y Legales.

95.- Proyecto de ordenanza 95/24: “Adjudicar inmuebles barrio Habana”. Autor: Intendente Municipal, Walter Cortés. Colaborador: Secretario de Capital Humano, Acción Social y Deporte Hector Fabian Zuniga. Se gira a Asesoría Letrada y a las comisiones de Obras y Planeamiento y de Gobierno y Legales. O-24-3481 Acta 1197/24 del 19/12/24.

96.- Proyecto de ordenanza 96/24: “Nuevo requisito de antigüedad en unidades de transporte. Modifica artículos de ordenanzas”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Iniciativa: Asociación de Transportistas.  Se gira a Asesoría Letrada y a las comisiones de Servicios, Tránsito y Transporte y de Gobierno y Legales. Prioridad de dictamen (Legislativa del 03-07-24. Acta 16/24) O-24-3462 Acta 1192/24 del 22/08/24.

97.- Proyecto de declaración 97/24: “Se declara de interés municipal la 7° Muestra de Carreras de Educación Superior Pública” Autores: Concejales Gerardo Del Río, Maria Coronado y Tomas Hercigonja (PUL). Iniciativa: CRUB. Sobre tablas D-24-2998 Acta 1190/24 del 30/05/24.

98.- Proyecto de declaración 98/24: “Se declara de interés municipal charla  Nado en aguas abiertas a cargo de Mayte Puca”. Autores: Concejales Tomás Hercigonja, Gerardo Del Río y María Coronado (PUL). Iniciativa: Cintia Proverbio. Sobre tablas. D-24-2999 Acta 1190/24 del 30/05/24.

99.- Proyecto de declaración 99/24: “Se declara de interés municipal la séptima edición de la Expo Puri Vino BRC 2024”. Autora: Concejala Natalia Almonacid (JSRN). Iniciativa: Nicolas Noceti y Rebeca Leal Díaz, organizadores de la Expo Puro Vino BRC 2024. Sobre tablas. D-24-3000 Acta 1190/24 del 30/05/24.

100.- Proyecto de ordenanza 100/24: “Se incorpora artículos 38°-39° al anexo II de la ordenanza 1747-CM-07. Asigna nombre a plazas parque coirones y vecinos unidos”. Autora: Concejala Natalia Almonacid (JSRN). Se gira a Asesoría Letrada y a las comisión de Gobierno y Legales. Prioridad de dictamen (Legislativa del 03-07-24. Acta 16/24) O-25-3490 Acta 1201/25 del 20/03/25.

101.- Proyecto de ordenanza 101/24: “De desafecta dominio público municipal y se afecta a dominio privado fraccionamiento de 827,91 m2 lindera a la parcela 19-2-B-013-01”. Autor: Intendente Municipal Walter Cortés. Colaborador: Secretario de Planeamiento Territorial, Alfo Nestor Painemil. Se gira a Asesoría Letrada y a las comisiones de Obras y Planeamiento y de Gobierno y Legales.

102.- Proyecto de ordenanza 102/24: “Autorizar fraccionamiento manzana 187 lote 02 Barrio Unión. Regularizar”. Autor: Intendente Municipal Walter Cortés. Colaborador: Instituto Municipal de Tierras y Vivienda para el Hábitat Social. Se gira Asesoría Letrada y a las comisiones de Obras y Planeamiento y de Gobierno y Legales. O-24-3471 Acta 21/11/24 del 21/11/24.

103.- Proyecto de ordenanza 103/24: “Se instituye la guía de interpretación de usos del suelo”. Autores: Concejales Leandro Costa Brutten (Incluyendo Bariloche). Colaboradores: Carolina Costa y Juan Ramírez. Se gira a Asesoría Letrada y a las comisiones de Obras y Planeamiento y de Gobierno y Legales.

104.- Proyecto de comunicación 104/24: “Se comunica la necesidad de apoyo comunitario para evitar desalojos de familias y Club Puerto Moreno”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre tablas. C-24-1130 Acta 1190/24 del 30/05/24.

105.- Proyecto de ordenanza 105/24: “Modifica Consejo Municipal de Juventudes”. Autora: Concejala Julieta Wallace (Incluyendo Bariloche). Iniciativa: Juventud Peronista Bariloche. Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales.

106.- Proyecto de ordenanza 106/24: “Declara de interés social anteproyecto fraccionamiento loteo Unión de Trabajadores de Entidades Deportivas y Civiles. NC 19-3-A-458-C”. Autor: Juan Pablo Ferrari (JSRN). Iniciativa: Unión Trabajadores de Entidades Deportivas y Civiles (UTEDyC).  Se gira a Asesoría Letrada y a las comisiones de Obras y Planeamiento y de Gobierno y Legales.

107.- Proyecto de ordenanza 107/24: “Se modifican ordenanzas 1931-CM-09 y 2375-CM-12”. Autora: Concejala Roxana Ferreyra (Nos Une). Se gira a Asesoría Letrada y a las comisiones de Economía, Hacienda, Finanzas y Desarrollo Económico, de Servicios, Tránsito y Transporte y de Gobierno y Legales. (Tratamiento en Conjunto comisiones de Economía y de Servicios Acta 13/24 comisión Legislativa).

108.- Proyecto de ordenanza 108/24: “Declara patrimonio histórico y cultural los retratos de intendentes de San Carlos de Bariloche”. Autor: Intendente Municipal Walter Cortés. Colaboradores: Secretario de Capital Humano, Acción Social y Deporte, Fabián Zúñiga y Subsecretaría de Cultura, Diana Garrafa. Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales
109.- Proyecto de ordenanza 109/24: “Se autoriza firma convenio de comodato con la junta vecinal Villa Don Orione”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche. Iniciativa: Junta vecinal Villa Don Orione. Se gira Asesoría Letrada y a las comisiones de Obras y Planeamiento y de Gobierno y Legales.
110.- Proyecto de comunicación 110/24: “La inmediata necesidad de confirmación de continuidad del Programa de Esquí Escolar”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre tablas.  Rechazado Acta 1191/24 del 04/07/24.
111.- Proyecto de declaración 111/24: “Se declara de interés municipal el VI Encuentro Nacional Rosa 2024”. Autor: Concejal Gerardo Del Río (PUL). Iniciativa: Asociación civil Nahuel Rosa de Bote Dragón. Sobre tablas. D-24-3006 Acta 1191/24 del 04/07/24.
112.- Proyecto de ordenanza 112/24: “Se regula publicidad y promoción de los juegos de azar y/o apuestas para prevenir ludopatía”. Autora: Concejala Julieta Wallace (Incluyendo Bariloche). Iniciativa: Juventud Peronista Bariloche. Se gira a Asesoría Letrada y a las comisiones de Desarrollo Humano, Deportes y Cultura y de Gobierno y Legales. O-24-3477 Acta 1197/24 del 19/12/24.
113.- Proyecto de ordenanza 113/24: “Se establece la rezonificación de los casinos”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Se gira a Asesoría Letrada y a las comisiones de Obras y Planeamiento y de Gobierno y Legales.
114.- Proyecto de ordenanza 114/24: “Modifica vigencia licencias de conducir. Se actualizan clases conforme legislación nacional vigente”. Autora: Concejala Laura Totonelli (JSRN). Iniciativa: Norberto Bianchi. Se gira a Asesoría Letrada y a las comisiones de Servicios, Tránsito y Transporte y de Gobierno y Legales.
115.- Proyecto de comunicación 115/24: “Se comunica la necesidad de franja de protección lacustre”. Autor: Concejal Facundo Blanco Villalba (Primero Río Negro). Iniciativa: Juan Ignacio Acuña. Sobre tablas. C-24-1131 Acta 1191/24 del 04/07/24.
116.- Proyecto de comunicación 116/24: “Se comunica necesidad de reactivar obras de integración socio urbana en barrios populares”. Autores: Concejales Leandro Costa Brutten, Julieta Wallace (Incluyendo Bariloche) y Roxana Ferreyra (Nos Une). Iniciativa: Mesa de Barrios Populares de Río Negro, Mesa de Barrios Populares de Bariloche (MBPB) y Movimiento de Trabajadores Excluidos (MTE). Sobre tablas. C-24-1132 Acta 1191/24 del 04/07/24.
117.- Proyecto de ordenanza 117/24: “Se asigna nombre Celestino Quijada al Concurso de Hacheros”. Autora: Concejala Roxana Ferreyra (Nos Une). Iniciativa: Comunidad Mapuche Lof Celestino Quijada. Sobre tablas. O-24-3459 Acta 1191/24 del 04/07/24.
118.- Proyecto de ordenanza 118/24: “Protocolo para la transparencia y regulación de la publicidad oficial”. Autor: Concejal Facundo Blanco Villalba (Primero Río Negro). Se gira Asesoría Letrada y a la comisión de Gobierno y Legales. O-24-3478 Acta 1197/24 del 19/12/24. VETADA POR LA RESOLUCIÓN 10-I-25 Acta 1198/25 del 13/02/25 se aceptó el veto.
119.- Proyecto de comunicación 119/24: “Se comunica la importancia de contratar artistas locales en la Fiesta de la Nieve”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre tablas. C-24-1133 Acta 1191/24 del 04/07/24.
120.- Proyecto de ordenanza 120/24: “Incorporar en Código de Edificación Urbana apartado para construcciones con contenedores marítimos”. Autores: Concejales Juan Pablo Ferrari y Laura Totonelli (JSRN). Colaboradores: Dirección de Obras Particulares y Dirección de Inspección General. Se gira a Asesoría Letrada y a las comisiones de Obras y Planeamiento y de Gobierno y Legales. Prioridad de dictamen (Legislativa del 03-07-24. Acta 16/24). O-24-3479 Acta 1197/24 del 19/12/24.
121.- Proyecto de ordenanza 121/24: “Conductor designado”. Autores: Concejales Laura Totonelli, Natalia Almonacid y Juan Pablo Ferrari (JSRN). Se gira a Asesoría Letrada y a las comisiones de Servicios, Tránsito y Transporte e Gobierno y Legales.
122.- Proyecto de declaración 122/24: “Se declara de interés municipal, comunitario y social la investigación Napoleón Argentino Araneda”. Autora: Concejala Julieta Wallace (Incluyendo Bariloche). Sobre tablas. D-24-3007 Acta 1191/24 del 04/07/24.
123.- Proyecto de resolución 123/24: “Se reglamentan transmisiones de sesiones en vivo”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales. R-24-732 Acta 1197/24 del 19 de diciembre de 2024.
124.- Proyecto de declaración 124/24: “Se declara de interés municipal la charla Un recorrido por la vida y el pensamiento político del Che Guevara”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Iniciativa: Máximo Schneebeli Grupo Bariloche de Solidaridad con Cuba. Sobre tablas. D-24-3005 Acta 1191/24 del 04/07/24.
125.- Proyecto de ordenanza 125/24: “Áreas de servicios para casas rodantes motorhomes, campers y similares”. Autora: Concejal Samanta Echenique (JxC). Se gira a Asesoría Letrada y a las comisiones de Economía, Hacienda, Finanzas y Desarrollo Económico; de Servicios, Tránsito y Transporte y de Gobierno y Legales. (Acta 40/25 Leg. del 05/03/25 Com. Turismo y Medio Ambiente, Economía, Servicios y Gobierno).
126.- Proyecto de declaración 126/24: “Se declara de interés municipal XVI Edición Programa Uniendo Metas Jóvenes para el Futuro. Asociación Conciencia”. Autor: Concejal Gerardo Del Río (PUL). Iniciativa: Comité Organizador Uniendo Metas de la Asociación Conciencia Bariloche. Sobre tablas. D-24-3008 Acta 1191/24 del 04/07/24.
127.- Proyecto de ordenanza 127/24: “Se crea en el ejido de Bariloche la modalidad de transporte compartido”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Se gira a Asesoría Letrada y a las comisiones de Economía, Hacienda, Finanzas y Desarrollo Económico; de Servicios, Tránsito y Transporte y de Gobierno y Legales.
128.- Proyecto de ordenanza 128/24: “Modifica ordenanza 194-CM-86. Amplía participación vecinal”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales. Girado a Comisión de Gobierno y Legales Acta 1202/25 del 22/05/25.
129.- Proyecto de ordenanza 129/24: “Deroga ordenanza 1023-CM-00”. Autores: Concejales Natalia Almonacid, Juan Pablo Ferrari y Laura Totonelli (JSRN). Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales.
130.- Proyecto de ordenanza 130/24: “Se establece el horario inclusivo obligatorio en todos aquellos establecimientos con atención al público”. Autores: Concejales Natalia Almonacid, Juan Pablo Ferrari y Laura Totonelli (JSRN). Colaboradores: Helen Tobar y Fiorella Scelatto, Inclusión Sur, TDG TEA Padres Bariloche. Se gira a Asesoría Letrada y a las comisiones de Economía, Hacienda, Finanzas y Desarrollo Económico y de Gobierno y Legales.
131.- Proyecto de ordenanza 131/24: “Modifica anexo I ordenanza 1747-CM-07. Se asigna, amplia denominación calles”. Autores: Concejales Natalia Almonacid, Juan Pablo Ferrari y Laura Totonelli (JSRN). Iniciativa: Vecinos 136 viviendas. Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales. O-24-3472 Acta 1196/24 del 21/11/24.
132.- Proyecto de comunicación 132/24: “Comunica al Congreso de la Nación necesidad de modificar fecha ley nacional 24374 y ley provincial 3396”. Autores: Concejales Leandro Costa Brutten y Julieta Wallace (Incluyendo Bariloche). Iniciativa: Consejo Social de Tierras. Sobre tablas. C-24-1134 Acta 1191/24 del 04/07/24.
133.- Proyecto de ordenanza 133/24: “Se modifica anexo I ordenanza 1629-CM-06. Antigüedad automotores servicio público de automóviles de alquiler con taxímetro”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Se gira a Asesoría Letrada y a las comisiones de Servicios, Tránsito y Transporte y de Gobierno y Legales.
134.- Proyecto de ordenanza 134/24: “Creación concurso Un Proyecto para mi Barrio. Fiesta Nacional de la Nieve”. Autores: Concejales Laura Totonelli y Juan Pablo Ferrari (JSRN). Se gira a Asesoría Letrada y a la Comisión de Gobierno y Legales. O-25
135.- Proyecto de ordenanza 135/24: “Derogar Ecotasa, artículos 117-118 y 362- 371 de las ordenanzas 2375-CM-12 y 2374-CM-12”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Se gira a Asesoría Letrada y a las comisiones de Economía, Hacienda, Finanzas y Desarrollo Económico y de Gobierno y Legales. Tratamiento en conjunto Proyecto 156/24 y 195/24 (Legislativa del 2-10-24 Acta 25/24.) O-25-3487 Acta 1199/25 del 6/3/25.
136.- Proyecto de comunicación 136/24: “Se comunica rotunda oposición al proyecto de baja de edad de imputabilidad”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Colaboradora: Mabel Oviedo, miembro de la Red de Bibliotecas Bariloche. Sobre tablas. C-24-1136 Acta 1192/24 del 22/08/24.
137.- Proyecto de comunicación 137/24: “Se comunica el rechazo al Régimen de Incentivo a las Grandes Inversiones (RIGI)”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Colaboradora: Andrea Galaverna. Se gira a Asesoría Letrada y a la Comisión de Gobierno y Legales.  Prioridad de dictamen (Legislativa del 21-08-24. Acta 19/24).
138.- Proyecto de ordenanza 138/24: “Se modifica anexo I ordenanza 1747-CM-07. Asigna denominación a calles de Mirador del Challhuaco”. Autor: Concejal Facundo Blanco Villalba (Primero Río Negro). Se gira a Asesoría Letrada y a la Comisión de Gobierno y Legales.  Preferencia de dictamen (Acta 27/24 Comisión Legislativa del 16-10-24).  O-24-3473 Acta 1196/24 del 21/11/24.
139.- Proyecto de ordenanza 139/24: “Aceptar donación de tablet, memoria ram y soporte micrófono”. Autor: Intendente Municipal Walter Cortés. Colaboradores: Secretario de Capital Humano, Acción Social y Deportes, Héctor Fabián Zúñiga; Subsecretaría de Cultura, Diana Garrafa; Coordinador General de la Subsecretaría de Cultura, Gustavo Gaminao y Micaela Giménez del Departamento Administrativo de la Subsecretaría de Cultura. Sobre tablas. O-24-3464 Acta 1192/24 del 22/08/24.
140.- Proyecto de ordenanza 140/24: “Aceptar donación de pantalla para proyector con control remoto”. Autor: Intendente Municipal Walter Cortés. Colaboradores: Secretario de Capital Humano, Acción Social y Deportes, Héctor Fabián Zúñiga; Subsecretaria de Cultura, Diana Garrafa; Coordinador General de la Subsecretaría de Cultura, Gustavo Gaminao y Micaela Giménez del Departamento Administrativo de la Subsecretaría de Cultura. Sobre tablas. O-24-3465 Acta 1192/24 del 22/08/24.
141.- Proyecto de ordenanza 141/24: “Se crea registro municipal de comedores y merenderos comunitarios”. Autora: Concejal Julieta Wallace (Incluyendo Bariloche). Iniciativa: Juventud Peronista Bariloche. Se gira a Asesoría Letrada y a la Comisión de Gobierno y Legales.

142.- Proyecto de ordenanza 142/24: “Creación Área Natural Protegida Cerro Catedral-Cerro San Martín-Altas Cuencas Bariloche”. Autora: Concejala Julieta Wallace (Incluyendo Bariloche). Colaboradoras: Marina Stecconi, Julieta Massaferro y Sofía Bordenave. Se gira a Asesoría Letrada y a las comisiones de Turismo y Medio Ambiente y de Gobierno y Legales.
143.- Proyecto de ordenanza 143/24: “Adhesión al Régimen de Incentivo de Grandes Inversiones (RIGI)”. Autora: Concejal Samanta Echenique (JxC). Se gira a Asesoría Letrada y a la Comisión de Gobierno y Legales. Prioridad de dictamen (Legislativa del 21-08-24. Acta 19/24).
144.- Proyecto de ordenanza 144/24: “Se modifica la ordenanza 3044-CM-19. Regula disponibilidad de chatarra”. Autora: Concejala Laura Totonelli (JSRN). Se gira a Asesoría Letrada y a las comisiones de Servicios, Tránsito y Transporte y de Gobierno y Legales. O-25-3497 Acta 1202/25 del 22/05/25.
145.- Proyecto de ordenanza 145/24: “Se encomienda relevamiento social en vertedero. Crea programa de asistencia alimentaria”. Autora: Concejala Julieta Wallace (Incluyendo Bariloche). Colaboradores: Juventud Peronista Bariloche. Se gira a Asesoría Letrada y a las comisiones de Desarrollo Humano, Deportes y Cultura y de Gobierno y Legales.
146.- Proyecto de ordenanza 146/24: “Autoriza fraccionamiento loteo NC 19-3-A-022-002. Declara de interés social. Sindicato de Luz y Fuerza de Bariloche”. Autores: Concejales Natalia Almonacid, Juan Pablo Ferrari, Laura Totonelli (JSRN), Leandro Costa Brutten (Incluyendo Bariloche), Facundo Blanco Villalba (Primero Río Negro) y Samanta Echenique (JxC). Se gira a Asesoría Letrada y a las comisiones de Obras y Planeamiento y de Gobierno y Legales. O-25-3513 Acta 1206/25 del 03/07/25.
147.- Proyecto de declaración 147/24: “Se declara de interés cultural, social, comunitario el 28° aniversario de Radio Imperio”. Autor: Concejal Facundo Blanco Villalba (Primero Río Negro). Sobre tablas. D-24-3012 Acta 1192/24 del 22/08/24.
148.-Proyecto de ordenanza 148/24: “Regula servicio de volquetes”. Autoras: Concejalas Laura Totonelli y Natalia Almonacid (JSRN). Se gira a Asesoría Letrada y a las comisiones de Servicios, Tránsito y Transporte y de Gobierno y Legales. O-25-3514 Acta 1206/25 del 03/07/25.
149.- Proyecto de declaración 149/24: “Se declara de interés municipal la 1° Feria Rasonar”. Autores: Comisión Legislativa, concejales Gerardo Del Río, Tomás Hercigonja (PUL); Samanta Echenique (JxC); Leandro Costa Brutten (Incluyendo Bariloche) y Facundo Blanco Villalba (Primero Río Negro). Sobre tablas. D-24-3013 Acta 1192/24 del 22/08/24.
150.- Proyecto de comunicación 150/24: “Se comunica la necesidad de activar el Consejo Local Consultivo para Personas con Discapacidad”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Colaboradora: Mabel Noemí Oviedo. Sobre tablas. C-24-1135 Acta 1192/24 del 22/08/24.
151.- Proyecto de ordenanza 151/24: “Autorizar planteo urbanístico 19-2-P-247. Barrio 2 de Abril. Regularización”. Autor: Intendente Municipal Walter Cortés. Colaboradores: Secretaria de Planeamiento Territorial, María Sofía Maggi e Instituto Municipal de Tierra y Vivienda para el Hábitat Social. Se gira a Asesoría Letrada y a las comisiones de Obras y Planeamiento y de Gobierno y Legales.
152.- Proyecto de ordenanza 152/24: “Modifica ordenanza 1994-CM-09. Consejo de Planeamiento Estratégico y Unidad Planeamiento Estratégico”. Autora: Concejala Julieta Wallace (Incluyendo Bariloche). Se gira a Asesoría Letrada y a las comisiones de Obras y Planeamiento y de Gobierno y Legales.
153.- Proyecto de declaración 153/24: “Se declara de interés municipal la 12° Edición del Festival Audiovisual Bariloche”. Autor: Concejal Gerardo Del Río (PUL). Iniciativa: Subsecretaría de Cultura, Diana Garrafa y Jefa del Departamento Administrativo, Graciela Chodilef. Sobre tablas. D-24-3014 Acta 1192/24 del 22/08/24.
154.- Proyecto de ordenanza 154/24: “Se modifica ordenanza 3236-CM-21”. Autores: Concejales Natalia Almonacid (JSRN) y Gerardo Del Río (PUL). Coautores: Concejales Juan Pablo Ferrari, Laura Totonelli (JSRN), María del Carmen Coronado y Tomás Hercigonja (PUL). Sobre tablas. O-24-3463 Acta 1192/24 del 22/08/24.
155.- Proyecto de ordenanza 155/24: “Se crea la Comisión Municipal de Boxeo”. Autores: Concejales Gerardo Del Río, Tomás Hercigonja y María del Carmen Coronado (PUL). Iniciativa: Escuelas de boxeo de Bariloche. Se gira a Asesoría Letrada y a las comisiones de Desarrollo Humano, Deportes y Cultura y de Gobierno y Legales. 
156.- Proyecto de ordenanza 156/24: “Se establece la Contribución Verde de Sostenimiento Ambiental (COVERSA) en el ejido municipal”. Autora: Concejala Roxana Ferreyra (Nos Une). Colaboradores: Arquitecto Raúl Martiniau. A Asesoría Letrada y a las comisiones de Economía, Hacienda, Finanzas y Desarrollo Económico, de Turismo y Medio Ambiente y de Gobierno y Legales. Prioridad de dictamen y tratamiento en conjunto Economía y Turismo (Legislativa del 21-08-24. Acta 19/24). (Legislativa 02/10/27 Acta 25/20) cambio de ruta legislativa Turismo y Medio Ambiente, Economía y Gobierno. 
157.- Proyecto de declaración 157/24: “Declarar de interés municipal a Radio Club Bariloche”. Autor: concejal Leandro Costa Brutten (Incluyendo Bariloche). Colaboradores: Comisión Directiva del Radio Club Bariloche LUV1IZ. Sobre tablas.  D-24-3015 Acta 1192/24 del 22/08/24.
158.- Proyecto de declaración 158/24: “Se declara de interés a la Asociación de Fútbol de Bariloche ADEFUL”. Autor: concejal Leandro Costa Brutten (Incluyendo Bariloche). Colaboradores: Comisión Directiva ADEFUL. Sobre tablas. D-24-3016 Acta 1192/24 del 22/08/24.
159.- Proyecto de ordenanza 159/24: “Aprueba plan de composición urbana parcela 19-2-F-017-03” Autor: Intendente Municipal Walter Cortes. Colaboradora: Secretaria de Planeamiento Territorial, María Sofía Maggi.  Se gira a Asesoría Letrada y a las comisiones de Obras y Planeamiento y de Gobierno y Legales.
160.- Proyecto de ordenanza 160/24:“Crea Registro Árboles Singulares y Comisión Arbolado Público y Árboles Singulares”. Autora: Concejala Julieta Wallace (Incluyendo Bariloche). Colaboradores: Marcela Ferreyra, Liliana Schiavo, Adriana Rovere, Leonardo Gallo, Juan José Paternó y Marina Stecconi. Se gira a Asesoría Letrada y a las comisiones de Servicios, Tránsito y Transporte y de Gobierno y Legales.
161.- Proyecto de declaración 161/24: “Se declara de interés municipal y comunitario la película Estepa”. Autora: Concejala Roxana Ferreyra (Nos Une). Sobre Tablas. D-24-3022 Acta 1193/24 del 12/09/24.
162.- Proyecto de declaración 162/24: “Se declara de interés municipal y comunitario la Sexta Escuela Avanzada José A. Balseiro. Protección Radiológica 2024”. Autora: Concejala Roxana Ferreyra (Nos Une). Iniciativa: Pablo Andrés, profesor adjunto de la cátedra Protección Radiológica CNEA-IB. Sobre tablas. D-24-3023 Acta 1193/24 del 12/09/24.
163.- Proyecto de comunicación 163/24: “Se comunica la necesidad de restablecer el normal funcionamiento del Tribunal de Faltas Municipal”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre tablas. Retirado Acta 1193/24 del 12/09/24.
164.- Proyecto de comunicación 164/24: “Se comunica al Poder Ejecutivo de la Provincia la necesidad de designación de un docente especializado en instrumentos musicales de orquesta”. Autora: Concejal Samanta Echenique (JXC). Iniciativa: John Keen. Sobre tablas. C-24-1137 Acta 1193/24 del 12/09/24.
165.- Proyecto de ordenanza 165/24: “Se establece como obligatorio certificado psicofísico para planta política”. Autor: Concejal Facundo Blanco Villalba (Primero Río Negro). Se gira a Asesoría Letrada y a la Comisión de Gobierno y Legales.
166.- Proyecto de resolución 166/24: “Asignar el nombre de Alberto ‘Beto’ Icare al despacho 19 del Concejo Municipal”. Autor: Concejal Facundo Blanco Villalba (Primero Río Negro). Sobre tablas. R-24-718 Acta 1193/24 del 12/09/24.
167.- Proyecto de declaración 167/24: “Se declara de interés municipal el 14° Congreso Argentino de Física Médica”. Autores: Comisión Legislativa: Concejales: Gerardo Del Río (PUL), Roxana Ferreyra (Nos Une), Facundo Blanco Villalba (Primero Río Negro) y Samanta Echenique (JxC). Iniciativa: Responsable Física de Medicina Nuclear, Intecnus-Conea Virginia Venier. Sobre tablas. D-24-3024 Acta 1193/24 del 12/09/24.
168.- Proyecto de ordenanza 168/24: “Se modifica ordenanza 2546-CM-14. Se reconoce y otorga personería jurídica a la junta vecinal Mirador del Chalhuaco”. Autor: Concejal Facundo Blanco Villalba (Primero Río Negro). Colaboradores: Comisión promotora de la junta vecinal barrio Mirador del Chalhuaco. Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales. Preferencia de dictamen (Acta 27/24 Comisión Legislativa).  
169.- Proyecto de ordenanza 169/24: “Autoriza Planteo Urbanístico 19-2-K-014-01. Declara de interés social. Adjudica”. Autor: Intendente municipal, Walter Cortés. Colaboradores: Instituto Municipal de Tierra y Vivienda para el Hábitat Social y Secretaria de Planeamiento Territorial, Sofía Maggi. Se gira a Asesoría Letrada y a las comisiones de Obras y Planeamiento y de Gobierno y Legales.  (barrio El Maitén)
170.- Proyecto de ordenanza 170/24: “Control y prevención de la contaminación acústica y ruidos molestos”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Iniciativa: Andrea Galaverna. Colaborador: Juan Ramírez. Se gira a Asesoría Letrada y a las comisiones de Economía, Hacienda, Finanzas y Desarrollo Económico; Servicios, Tránsito y Transporte y de Gobierno y Legales.
171.- Proyecto de ordenanza 171/24: “Se modifican anexo I ordenanza 2375-CM-12 y ordenanza 2934-CM-18”. Autora: Concejala Natalia Almonacid (JSRN). Iniciativa: Comisión Fílmica Bariloche. Se gira a Asesoría Letrada y a las comisiones de Economía, Hacienda, Finanzas y Desarrollo Económico y de Gobierno y Legales. O-25-3494 Acta 1201/25 del 20/03/25.
172.- Proyecto de ordenanza 172/24: “Crear el registro de conductores de vehículos inhabilitados y suspendidos”. Autores: Concejales Laura Totonelli, Natalia Almonacid y Juan Pablo Ferrari (JSRN). Se gira a Asesoría Letrada y a las comisiones de Servicios, Tránsito y Transporte y de Gobierno y Legales.
173.-Proyecto de ordenanza 173/24: “Regula el servicio de transporte a través de plataformas digitales”. Autores: Concejales Gerardo Del Río, Tomas Hercigonja y Maria del Carmen Coronado (PUL). Se gira a Asesoría Letrada y a las comisiones de Economía, Hacienda, Finanzas y Desarrollo Económico; Servicios, Tránsito y Transporte  y  de Gobierno y Legales.
174.- Proyecto de comunicación 174/24: “Se comunica rechazo al veto presidencial de la Ley de Movilidad Jubilatoria”. Autora: Concejala Roxana Ferreyra (Nos Une). Iniciativa: Jubilados y jubiladas de San Carlos de Bariloche. Sobre tablas. C-24-1138 Acta 1193/24 del 12/09/24.
175.- Proyecto de ordenanza 175/24: “Incorpora perspectiva de género. Modifica ordenanza 1815-CM-08. Incorpora inciso h al artículo 4°”. Autora: Concejala Julieta Wallace (Incluyendo Bariloche). Colaboradores: Juventud Peronista Bariloche. Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales. O-25-3506 Acta 1205/25 del 12/06/25.
176.- Proyecto de comunicación 176/24: “Se comunica necesidad de aumento partida Asociación Grupo Encuentro”. Autora: Concejala Julieta Wallace (Incluyendo Bariloche). Iniciativa: Grupo Encuentro. Sobre tablas. C-24-1139 Acta 1193/24 del 12/09/24.
177.- Proyecto de ordenanza 177/24: “Autorizar planteo urbanístico 19-2-P-286-01 B° 2 de abril. Regularización” Autor: Intendente municipal, Walter Cortés. Colaboradores: Instituto Municipal de Tierra y Vivienda para el Hábitat Social y Secretaria de Planeamiento Territorial, Sofía Maggi. Se gira a Asesoría Letrada y a las comisiones de Obras y Planeamiento y de Gobierno y Legales.
178.- Proyecto de ordenanza 178/24: “Autorizar planteo urbanístico 19-2-E-039-01. B° manzana Hueney. Regularización”. Autor: Intendente municipal, Walter Cortés. Colaboradores: Instituto Municipal de Tierra y Vivienda para el Hábitat Social y Secretaria de Planeamiento Territorial, Sofía Maggi. Se gira a Asesoría Letrada y a las comisiones de Obras y Planeamiento y de Gobierno y Legales. (Prioridad de dictamen Legislativa 20/11/2024 Acta 32/24).
179.- Proyecto de ordenanza 179/24: “Se modifica el anexo I ordenanza 3440-CM-24. Presupuesto año 2024”. Autor: Intendente Municipal, Walter Cortés. Colaboradora: Secretaria de Hacienda, Carina Ondarcuhu. Sobre tablas. O-24-3470 Acta 1194/24 del 3/10/24.
180.- Proyecto de ordenanza 180/24: “Facultar al Ejecutivo de herramientas para normalizar el Estado Municipal”. Autor: Intendente Municipal, Walter Cortés. Colaboradora: Secretaria de Hacienda, Carina Ondarcuhu. Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales.
181.- Proyecto de ordenanza 181/24: “Se modifica artículo 29° inciso b) Anexo I de la ordenanza Tarifaria 2375-CM-12 y sus modificatorias”. Autor: Intendente Municipal, Walter Cortés. Colaboradora: Secretaria de Hacienda, Carina Ondarcuhu. Se gira a Asesoría Letrada y a las comisiones de Economía, Hacienda, Finanzas y Desarrollo Económico y de Gobierno y de Legales.
182.- Proyecto de ordenanza 182/24: “Se modifica ordenanza 1815-CM-08. Deroga ordenanza 134-CM-92”. Autor: Intendente Municipal, Walter Cortés. Colaboradores: Instituto Municipal de Tierra y Vivienda para el Hábitat Social y secretaria de Planeamiento Territorial María Sofía Maggi. Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales. Prioridad de dictamen (Legislativa del 2-10-24. Acta 25/24). O-24-3480 Acta 1197/24 del 19/12/24.

183.- Proyecto de ordenanza 183/24: “Se establece el Día Nacional de la Biblia. Se modifica ordenanza 2033-CM-10”. Autores: Concejales Gerardo Del Río y María del Carmen Coronado (PUL). Iniciativa: Subsecretaría de Cultura de la Municipalidad de San Carlos de Bariloche. Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales.
184.- Proyecto de declaración 184/24: “Se declara de interés municipal el 16° Festival y Congreso Latinoamericano de Arte Hacia la Desmanicomialización”. Autores: Concejales Gerardo Del Río (PUL); Leandro Costa Brutten (Incluyendo Bariloche); Samanta Echenique (JxC) y Roxana Ferreyra (Nos Une). Iniciativa: Asociación Civil El Brote. Se solicitará su retiro por haberse emitido la resolución 350-PCM-24. Retirado Acta 1194/24 del 3/10/24.
185.- Proyecto de declaración 185/24: “Se declara de interés municipal evento Vení tal como sos”. Autor: Concejal Tomás Hercigonja (PUL). Iniciativa: representantes del grupo Iglesias en Bariloche. Sobre tablas. D-24-3028. Acta 1194/24 del 3/10/24.
186.- Proyecto de comunicación 186/24: “Se comunica la necesidad urgente de convocar audiencia pública para Plan Acceso Este”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre tablas. C-24-1140 Acta 1194/24 del 3/10/24.
187.- Proyecto de comunicación 187/24: “Se comunica repudio a la represión policial contra docentes en la Legislatura provincial”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre tablas. Rechazado Acta 1194/24 del 3/10/24.
188.- Proyecto de declaración 188/24: “Se declara de interés municipal y cultural a la Masterclass de Academia Superior de Taekwondo”. Autor: Concejal Juan Pablo Ferrari (JSRN). Iniciativa: Academia Superior de Taekwondo. Sobre tablas. D-24-3029 Acta 1194/24 del 3/10/24.
189.- Proyecto de ordenanza 189/24: “Abroga ordenanza 1509-CM-05”. Autor: Intendente Municipal, Walter Cortés. Colaboradora: Secretaria Legal y Técnica Yanina Sánchez. Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales.
190.- Proyecto de ordenanza 190/24: “Se aprueba Presupuesto Municipal año 2025”. Autor: Intendente Municipal Walter Cortés. Colaboradora: Secretaria de Hacienda, Carina Ondarcuhu. Se gira a Asesoría Letrada y a las comisiones de Economía, Hacienda, Finanzas y Desarrollo Económico y de Gobierno y  Legales. Prioridad de dictamen (Legislativa del 2-10-24. Acta 25/24). O-24-3482 Acta 1197/24 del 19/12/24.
191.- Proyecto de ordenanza 191/24: “Suspende permisos obras y mejoras. Crea reserva natural urbana Mallín del Km 12”. Autora: Concejala Julieta Wallace (Incluyendo Bariloche). Iniciativa: Asociación Civil Árbol de Pie Bariloche y Grace Haro. Se gira a Asesoría Letrada y a las comisiones de Turismo y Medio Ambiente, de Obras y Planeamiento y de Gobierno y Legales. Prioridad de dictamen y Tratamiento en conjunto comisiones Turismo y Obras (Legislativa del 2-10-24. Acta 25/24). (Acta 1197/24 del 19/12/24 se gira a la comisión de Gobierno y Legales)
192.- Proyecto de declaración 192/24: “Se declara de interés municipal Jornada de Concientización sobre el Cáncer de Mama”. Autores: Concejales María Coronado, Tomás Hercigonja y Gerardo Del Río (PUL). Colaboradores: Olga Vanesa Badilla y Agrupación Pelos al Viento. Sobre tablas. D-24-3030 Acta 1194/24 del 3/10/24.
193.- Proyecto de ordenanza 193/24: “Desafecta dominio público municipal. Autoriza comodato Liga de Fútbol Bariloche”. Autores: Concejales Natalia Almonacid y Laura Totonelli (JSRN). Colaborador: Carlos Sánchez y Puente. Iniciativa: Liga de Fútbol Bariloche (LIFUBA). Se gira a Asesoría Letrada y a las comisiones de Obras y Planeamiento y de Gobierno y Legales. 
194.- Proyecto de comunicación 194/24: “Se comunica necesidad cumplir con cupo de género en nominaciones a la CSJN”. Autora: Concejala Julieta Wallace (Incluyendo Bariloche). Colaboradores: Juventud Peronista Bariloche. Sobre tablas. C-24-1141 Acta 1194/24 del 3/10/24.
195.- Proyecto de ordenanza 195/24: “Incorpora contribución especial al turismo. Modifica ordenanzas 2374 y 2375-CM-12”. Autor: Intendente Municipal, Walter Cortés. Colaboradora: Secretaria de Hacienda, Carina Ondarcuhu. Se gira a Asesoría Letrada y a las comisiones de Economía, Hacienda, Finanzas y Desarrollo Económico y de Gobierno y Legales.  (Legislativa del 2-10-24. Acta 25/24) Prioridad de dictamen, Tratamiento en conjunto comisiones de Economía y Gobierno y Tratamiento en conjunto Proyectos 135/24 y 156/24.
196.- Proyecto de ordenanza 196/24: “Autoriza redistribución predial 19-2-H-H10-02A y 19-2-H10-003. Autoriza Proyecto Urbanístico Privado y Social. Aprueba parámetros urbanísticos. Ordenanza 3443-CM-24”. Autor: Intendente Municipal, Walter Cortés. Colaboradora: Secretaria de Planeamiento Territorial, Sofía Maggi. Se gira a Asesoría Letrada y a las comisiones de Obras y Planeamiento y de Gobierno y Legales. Prioridad de dictamen (Legislativa del 2-10-24. Acta 25/24). Obras y Gobierno en conjunto (Acta 1195/24). O-24-3483 Acta 1197/24 del 19/12/24.
197.- Proyecto de ordenanza 197/24: “Creación Programa de garantías de alquiler”. Autoras: Concejalas Laura Totonelli y Natalia Almonacid (JSRN). Se gira a Asesoría Letrada y a las comisiones de Economía, Hacienda, Finanzas y Desarrollo Económico y de Gobierno y de Legales.
198.- Proyecto de ordenanza 198/24: “Modifica el artículo 46° del anexo I de la Ordenanza 2546-CM-14”. Autor: Intendente Municipal Walter Cortés. Colaboradores: Dirección General de Juntas Vecinales, Secretaría de Planeamiento Territorial, Sofia Maggi y Junta Vecinal Tres Lagos. Se gira a Asesoría Letrada y a la Comisión de Gobierno y Legales.
199.- Proyecto de comunicación 199/24: “Se comunica el rechazo al veto presidencial a la ley de financiamiento universitario”. Autor: concejal Leandro Costa Brutten (Incluyendo Bariloche). Se solicitará su retiro. Retiro Acta 1195/24 del 31/10/24.
200.- Proyecto de ordenanza 200/24: “Se aprueba acuerdo compensación. Incorpora inmueble al Banco de Tierra Municipal”. Autor: Intendente Municipal Walter Cortés. Colaboradores: Director del Instituto Municipal de Tierra y Vivienda para el Hábitat Social, Secretaría Legal y Técnica, Comisión de Transacciones y Secretaria de Planeamiento Territorial, Sofia Maggi. Se gira a Asesoría Letrada y a las comisiones de Economía, Hacienda, Finanzas y Desarrollo Económico y de Gobierno y Legales.
201.- Proyecto de comunicación 201/24: “Se comunica al Ejecutivo Municipal solicitud para convocar comisión pase a planta”. Autor: concejal Leandro Costa Brutten (Incluyendo Bariloche). Iniciativa: Soyem. Sobre Tablas. C-24-1142 Acta 1195/24 del 31/10/24.
202.- Proyecto de ordenanza 202/24: “Autorizar planteo urbanístico 19-2-P-187-04 Barrio 2 de Abril. Declara de interés social”. Autor: Intendente Municipal Walter Cortés. Colaboradores: Instituto Municipal de Tierra y Vivienda para el Hábitat Social y Secretaria de Planeamiento Territorial, Sofia Maggi. Se gira a Asesoría Letrada y a las comisiones de Obras y Planeamiento y de Gobierno y Legales.
203.- Proyecto de declaración 203/24: “Se declara de interés municipal a las Jornadas Andinas Integrales de Neonatología”. Autor: Concejal Juan Pablo Ferrari (JSRN). Iniciativa: Hospital Zonal Bariloche, Sanatorio San Carlos, Instituto Materno Infantil y Sociedad Argentina de Pediatría. Sobre Tablas. D-24-3036 Acta 1195/24 del 31/10/24.

204.- Proyecto de declaración 204/24: “Se declara de interés municipal y cultural el evento Bariloche Not Moda”. Autor: Concejal Juan Pablo Ferrari (JSRN). Iniciativa: Jesica Beaudean y Jazmín Fernández Murgic. Sobre Tablas. D-24-3037 Acta 1195/24 del 31/10/24.
205.- Proyecto de declaración 205/24: “Declarar de interés municipal XII Jornada Federal de Asesoramiento Notarial Comunitario”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Iniciativa: Colegio Notarial de la Provincia de Río Negro. Sobre Tablas. D-24-3038 Acta 1195/24 del 31/10/24.
206.- Proyecto de declaración 206/24: “Se declara de interés municipal Encuentro Internacional Derecho al Hábitat y Bienes Comunes”. Autora: Concejala Julieta Wallace (Incluyendo Bariloche). Iniciativa: Cooperativa Amapolas. Sobre Tablas. D-24-3039 Acta 1195/24 del 31/10/24.
207.- Proyecto de declaración 207/24: “Se declara de interés municipal y comunitario el proyecto 30.000 pañuelos por la memoria”. Autora: Concejala Julieta Wallace (Incluyendo Bariloche). Iniciativa: Juventud Peronista Bariloche y Fundación Ambiente, Desarrollo y Hábitat Sustentables. Sobre Tablas. D-24-3040 Acta 1195/24 del 31/10/24.
208.- Proyecto de comunicación 208/24: “Se comunica el rechazo al veto presidencial a la ley de financiamiento universitario”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Colaboradora: Dra. Andrea Galaverna. Sobre Tablas. C-24-1143 Acta 1195/24 del 31/10/24.
209.- Proyecto de declaración 209/24: “Declara de interés municipal VI Congreso Latinoamericano Medios de Transporte por Cable”. Autor: Intendente Municipal, Walter Cortés. Colaboradores: Secretaria de Planeamiento Municipal, María Sofía Maggi y Director de Obras por Contrato, Ing. Pablo Sosa. Sobre Tablas.  Se solicitará su retiro por haberse emitido la resolución 397-PCM-24. Retirado Acta 1195/24 del 31/10/24.
210.- Proyecto de ordenanza 210/24: “Prevención y erradicación de la violencia laboral en el ámbito municipal abroga ordenanza 2245-CM-11.” Autor: Concejal Leandro Costa Brutten. Iniciativa: SOYEM Bariloche. Colaboradores: Defensoría del Pueblo. Se gira a Asesoría Letrada y a las comisiones de Desarrollo Humano, Deportes y Cultura y de Gobierno y Legales. O-25-3515 Acta 1206/25 del 03/07/25.
211- Proyecto de comunicación 211/24: “Se comunica y solicita la implementación del Programa Educativo, Laboral C.E.J.A.S.S. Mi Primer Trabajo” Autores: Concejales Gerardo del Río, Tomás Hercigonja y María del Carmen Coronado (PUL). Iniciativa: Hugo Cejas. Sobre Tablas. C-24-1144 Acta 1195/24 del 31/10/24.
212.- Proyecto de comunicación 212/24: “Se comunica la necesidad de intervención urgente por vulneración a la libertad de expresión”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre Tablas. C-24-1145 Acta 1195/24 del 31/10/24.
213.- Proyecto de declaración 213/24: “Se declara de interés municipal Jornada Educativa sobre Diabetes Mellitus”. Autores: Concejales Maria del Carmen Coronado y Tomas Hercigonja (PUL). Iniciativa: Dr. Diego Carulla. Colaborador: Dr. López Rivera. Sobre Tablas. D-24-3041 Acta 1195/24 del 31/10/24.
214.- Proyecto de comunicación 214/24: “Se comunica el rechazo de persecución y continuo ataque a la libertad de prensa”. Autor: Concejal Facundo Blanco Villalba (Primero Río Negro). Sobre Tablas.  C-24-1146 Acta 1195/24 del 31/10/24.
215.- Proyecto de ordenanza 215/24: “Modificación ordenanza 2375-CM-12, módulo fiscal”. Autora: concejal Samanta Echenique (JxC). Se gira a Asesoría Letrada y a las comisiones de Economía, Hacienda, Finanzas y Desarrollo Económico y de Gobierno y Legales. (con Prioridad de dictamen Com. Leg del 30/10/24 Acta 29/24).
216.- Proyecto de ordenanza 216/24: “Suspensión de obras en zonas de riesgo ambiental barrio Belgrano, Las Margaritas y Jardín Botánico”. Autor: Concejal Facundo Villalba (Primero Río Negro). Iniciativa: Junta Vecinal Barrio Belgrano. Se gira a Asesoría Letrada y a las comisiones de Obras y Planeamiento y de Gobierno y Legales.
217.- Proyecto de ordenanza 217/24: “Autoriza suscripción escritura traslativa de dominio loteo AMEC, DC 19-2-F-026-11A”. Autores: Concejales Tomás Hercigonja, Gerardo Del Río y María Coronado (PUL). Se gira a Asesoría Letrada y a la comisiones de Obras y Planeamiento y de Gobierno y Legales.
218.- Proyecto de comunicación 218/24: “Se comunica la necesidad de sostener y respetar en su totalidad la grilla horaria de los gimnasios municipales”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre tablas. C-24-1147 Acta 1196/24 del 21/11/24.
219.- Proyecto de ordenanza 219/24: “Se aprueba y reemplaza el anexo I de la ordenanza 2374-CM-12”. Autor: Intendente Municipal, Walter Cortés. Colaboradora: Secretaria de Hacienda, Carina Ondarcuhu. Se gira a Asesoría Letrada y a las comisiones de Economía, Hacienda, Finanzas y Desarrollo Económico y de Gobierno y Legales. (con Prioridad de dictamen Com. Legis. del 20/11/24 Acta 32/24 y Comisión en conjunto Eco. y Gob.). O-25-3495 Acta 1201/25 del 26/03/25
220.- Proyecto de ordenanza 220/24: “Se aprueban y reemplazan los anexos I y II de la ordenanza 2375-CM-12”. Autor: Intendente Municipal, Walter Cortés. Colaboradora: Secretaria de Hacienda, Carina Ondarcuhu. Se gira a Asesoría Letrada y a las comisiones de Economía, Hacienda, Finanzas y Desarrollo Económico y de Gobierno y Legales. (con Prioridad de dictamen Com. Leg del 20/11/24 Acta 32 /24 y Comisión en conjunto Eco. y Gob.). O-25-3496 Acta 1201/25 del 26/03/25.
221.- Proyecto de declaración 221/24: “Se declara de interés municipal Triatlón Escape Isla Huemul edición 2025”. Autores: Comisión Legislativa Concejales Gerardo Del Río, Tomas Hercigonja (PUL) y Facundo Villalba (Primero Río Negro). Iniciativa: Club Pehuenes. Sobre tablas. D-24-3046 Acta 1196/24 del 21/11/24.
222.- Proyecto de comunicación 222/24: “Se comunica al PEN rechazo a disolución de la AFIP según decreto 953/2024”. Autora: Concejala Roxana Ferreyra (Nos Une). Sobre tablas. C-24-1148 Acta 1194/24 del 21/11/24.
223.- Proyecto de comunicación 223/24: “Se comunica a Legislatura de Río Negro necesidad de tratamiento y aprobación del proyecto de ley 1215/2024”. Autores: Concejales Roxana Ferreyra (Nos Une); Julieta Wallace (Incluyendo Bariloche) y Juan Pablo Ferrari (JSRN). Sobre tablas. C-24-1149 Acta 1196/24 del 21/11/24.
224.- Proyecto de comunicación 224/24: “Se comunica solicitud dejar sin efecto sanciones al personal del Hospital Ramón Carrillo”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre tablas. C-24-1150 Acta 1196/24 del 21/11/24.
225.- Proyecto de declaración 225/24: “Se declara de interés municipal la 30° Edición del Pan Dulce Solidario”. Autora: Concejala Natalia Almonacid (JSRN). Sobre tablas. D-24-3047 Acta 1196/24 del 21/11/24.
226.- Proyecto de declaración 226/24: “Se declara de interés municipal la labor del Colegio de Arquitectos de Río Negro”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre tablas. D-24-3048 Acta 1196/24 del 21/11/24.
227.- Proyecto de declaración 227/24: “Se declara de interés municipal y cultural a la exposición Fragmentación y Territorio”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre tablas. D-24-3049 Acta 1196/24 del 21/11/24.
228.- Proyecto de declaración 228/24: “Se declara de interés municipal, cultural y comunitario a La Noche de los Museos Bariloche 2024”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre tablas. D-24-3050 Acta 1196/24 del 21/11/24.
229.- Proyecto de ordenanza 229/24: “Crea habilitación servicio diferencial de transporte público de pasajeros”. Autora: Concejala Laura Totonelli (JSRN). Iniciativa: Fundación de conductores particulares de Bariloche. Se gira a Asesoría Letrada y a las comisiones de Servicios, Tránsito y Transporte y de Gobierno y Legales.
230.- Proyecto de ordenanza 230/24: “Se crea programa certificado de escuelas verdes”. Autora: Concejala Laura Totonelli (JSRN). Iniciativa: Estudiantes Ailin Barrios, Tiara Toledo Porcel, Alejo Rogel, Valentín Filippi Farmar y docente Jorge Creusser, del Instituto Superior Patagónico. Se gira a Asesoría Letrada y a las comisiones de Desarrollo Humano, Deportes y Cultura y de Gobierno y Legales. O-25-3500 Acta 1202/25 del 22/05/25.
231.- Proyecto de declaración 231/24: “Se declara de interés municipal y deportivo la Carrera Bariloche Brut Running IX Edición 2024”. Autores: Concejales Gerardo Del Río y María del Cármen Coronado (PUL). Iniciativa: Nicolás Alberto Alfageme y Jessica Simoni, organizadores del Bariloche Brut Running. Sobre tablas. D-24-3051 Acta 1196/24 del 21/11/24.
232.- Proyecto de ordenanza 232/24: “Se crea régimen excepcional de regularización dominial de lotes sociales de dominio municipal y moratoria de pagos”. Autor: Intendente Municipal, Walter Cortés. Colaboradores: Secretaria Legal y Técnica, Yanina Sánchez e Instituto Municipal de Tierra y Vivienda para el Hábitat Social. Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales. (con Prioridad de dictamen Com. Leg del 20/11/24 Acta 32 /24).
233.- Proyecto de ordenanza 233/24: “Abroga ordenanza 502-CM-95”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Se gira a Asesoría Letrada y a la Comisión de Gobierno y Legales.  O-25-3499 Acta 1202/25 del 22/05/25. Vetada por la Resolución 1104-I-25. Acta 1204/25 Veto aceptado.
234.- Proyecto de ordenanza 234/24: “Se ratifica comodato ordenanza 1030-CM-00. Extiende convenio comodato Junta Vecinal - Policía Provincia de Río Negro”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Colaboradores: Vecinas y vecinos barrio Villa Los Coihues. Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales O-25-3491 Acta 1201/25 del 20/03/25
235.- Proyecto de ordenanza 235/24: “Se modifica ordenanza 2554-CM-24”. Autora: Concejala Roxana Ferreyra (Nos Une). Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales. O-25-3516 Acta 1206/25 del 03/07/25.
236.- Proyecto de resolución 236/24: “Se otorga premio al mérito y esfuerzo a la deportista María Rivera”. Autora: Concejala Roxana Ferreyra (Nos Une). Sobre Tablas. R-24-733 Acta 1197/24 del 19/12/24.
237.- Proyecto de ordenanza 237/24: “Modifica Código de Edificación - Área periférica microcentro (Área A2) - Edificaciones en subcentro calle Onelli (Área B) - Área residencial I (Área C) - Área O´Connor. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Se gira a Asesoría Letrada y a las comisiones de Obras y Planeamiento y de Gobierno y Legales.
238.- Proyecto de comunicación 238/24: “Se comunica a director de PAMI-INSSJP rechazo al recorte en medicamentos gratis”. Autora: Concejala Roxana Ferreyra (Nos Une). Sobre Tablas. C-24-1151 Acta 1197/24 del 19/12/24.
239.- Proyecto de ordenanza 239/24: “Se establece Día de Infancias y Adolescencias libres de etiquetas. Modifica ordenanza 2033-CM-10”. Autor: Concejal Gerardo Del Río (PUL). Iniciativa: Forum Infancias Zona Andina. Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales. O-25-3492 Acta 1201/25 del 20/03/25.
240.- Proyecto de declaración 240/24: “Se declara de interés municipal y cultural álbum musical infantil Un puente de canciones”. Autor: Concejal Juan Pablo Ferrari (JSRN). Iniciativa: Colegio Integral Vuriloche, docente Chela Painefil. Sobre Tablas. D-24-3058 Acta 1197/24 del 19/12/24.
241.- Proyecto de comunicación 241/24: “Se solicita al Poder Ejecutivo inmediatamente la restitución del acceso gratuito a medicamentos PAMI”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre Tablas. C-24-1152 Acta 1197/24 del 19/12/24.
242.- Proyecto de comunicación 242/24: “Se solicita al Ejecutivo Municipal la reglamentación de la ordenanza 3089-CM-19”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre Tablas. C-24-1153 Acta 1197/24 del 19/12/24.
243.- Proyecto de ordenanza 243/24: “Instalación de baños públicos en playas de la ciudad”. Autores: Concejales Juan Pablo Ferrari y Laura Totonelli (JSRN). Se gira a Asesoría Letrada y a las comisiones de Economía, Hacienda, Finanzas y Desarrollo Económico y de Gobierno y Legales.
244.- Proyecto de ordenanza 244/24: “Autoriza comodato inmueble 19-2-E-780-05 Casa la Gloria de Díos”. Autor: Intendente Municipal Walter Cortés. Colaboradores: Secretaria de Planeamiento Territorial Sofia Maggi. Iniciativa: Organización religiosa “Casa la Gloria de Dios”. Se gira a Asesoría Letrada y a las comisiones de Obras y Planeamiento y de Gobierno y Legales.
245.- Proyecto de comunicación 245/24: “Se comunica el rechazo y enérgico repudio a las prácticas antisindicales del Intendente”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre Tablas. C-24-1154 Acta 1197/24 del 19/12/24.
246.- Proyecto de ordenanza 246/24: “Se modifica ordenanza 1747-CM-07. Se nombran calles al barrio Bariloche del Este”. Autor: Concejal Facundo Blanco Villalba (Primero Río Negro). Iniciativa: Juan Manuel Valcarcel. Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales.
247.- Proyecto de ordenanza 247/24: “Convocar audiencia pública para Plan reestructuración urbana acceso Este”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Se gira a Asesoría Letrada y a las comisión de Gobierno y Legales.
248.- Proyecto de declaración 248/24: “Se declara de interés municipal Asociación Civil ENBHIGA (Asociación Civil Encuentro Bioceánico Hispano-Latino de Gastronomía)”. Autor: Concejal Juan Pablo Ferrari (JSRN). Iniciativa: Asociación Civil ENBHIGA. Sobre Tablas. D-24-3059 Acta 1197/24 del 19/12/24.
249.- Proyecto de ordenanza 249/24: “Se modifica la ordenanza 2554-CM-14: Ética de la función pública”. Autores: Concejales Juan Pablo Ferrari, Laura Totonelli, Natalia Almonacid (JSRN) y Samanta Echenique (JxC). Sobre Tablas. O-24-3484 Acta 1197/24 del 19/12/24.
250.- Proyecto de ordenanza 250/24: “Se prorroga la vigencia de las ordenanza 2374-CM-12 y 2375-CM-12”. Autor: Intendente Municipal Walter Cortés. Colaboradora: Secretaria de Hacienda Carina Ondarcuhu. Sobre Tablas. O-24-3485 Acta 1197/24 del 19/12/24.
251.- Proyecto de ordenanza 251/24: “Se incorpora artículo 38° al anexo II de la ordenanza 1747-CM-07. Asigna nombre a plaza Parque Carihue NC 19-2-C-140-2. Autora: Concejala Natalia Almonacid (JSRN). Iniciativa: Junta vecinal barrio Parque Carihue. Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales. O-25-3498 Acta 1202/25 del 22/05/25.
252.- Proyecto de ordenanza 252/25: “Se crea Área Natural Protegida Arroyo Casa de Piedra”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Colaboradores: Carlos Muzio y Comisión Medio Ambiente de las Juntas del Oeste de la Delegación Lago Moreno. Se gira a Asesoría Letrada y a las comisiones de Turismo y Medio Ambiente y de Gobierno y Legales.
253.- Proyecto de ordenanza 253/25: “Se prorroga Emergencia Habitacional. Ordenanza 3443-CM-24”. Autor: Intendente Municipal Walter Cortés. Colaboradora: Secretaria de Planeamiento Territorial, Sofia Maggi. Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales. (con Prioridad de dictamen Com. Leg del 5/3/25 Acta 40/25). Se gira a la Comisión  de Gobierno y Legales Acta 1202/25 del 22/05/25.
254.- Proyecto de resolución 254/25: “Se otorga premio al mérito y esfuerzo a la deportista Roxana Pescader”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre tablas. R-25-739 Acta 1199/25 del 6/3/25.
255.- Proyecto de ordenanza 255/25: “Se presta acuerdo llamado licitación pública provisión de 7.600 m³ leña de la zona Plan Calor 2025”. Autor: Intendente Municipal Walter Cortés. Colaborador: Secretario de Capital Humano, Acción Social y Deportes, Fabián Zuñiga. Sobre tablas. O-25-3488 Acta 1199/25 del 6/3/25.
256.- Proyecto de comunicación 256/25: “Se comunica al gobernador de Río Negro necesidad de garantizar avión hidrante para Zona Andina”. Autora: Concejala Julieta Wallace (Incluyendo Bariloche). Sobre tablas. C-25-1155 Acta 1199/25 del 6/3/25.
257.- Proyecto de resolución 257/25: “Se otorga distinción a la trayectoria y labor del profesor Santiago “Pancho” Navarro”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre tablas. R-25-740 Acta 1199/25 del 6/3/25.
258.- Proyecto de declaración 258/25: “Se declara de interés municipal el libro Iris un camino de lucha”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre tablas. D-25-3062 Acta 1199/25 del 6/3/25.
259.- Proyecto de declaración 259/25: “Se declara de interés municipal el Certamen Regional de Coctelería Bariloche 2025”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre tablas. D-25-3063 Acta 1199/25 del 6/3/25.
260.- Proyecto de declaración 260/25: “Se declara de interés municipal encuentro científico sobre magnetismo de partículas finas”. Autores: Concejales Laura Totonelli y Juan Pablo Ferrari (JSRN). Iniciativa: Roberto Zysler y Elin Winkler. Sobre tablas. D-25-3064 Acta 1199/25 del 6/3/25.
261.- Proyecto de ordenanza 261/25: “Se modifica ordenanza 1611-CM-06 Presupuesto Participativo”. Autora: Concejala Roxana Ferreyra (Nos Une). Se gira a Asesoría Letrada y a las comisiones de Economía, Hacienda, Finanzas y Desarrollo Económico y de Gobierno y Legales.
262.- Proyecto de declaración 262/25: “Declara de interés la participación de Sele Vera y Los Pampas en el Festival de Viña del Mar”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre tablas. D-25-3065 Acta 1199/25 del 6/3/25.
263.- Proyecto de declaración 263/25: “Se declara de interés municipal la iniciativa de FEEBA para el manejo responsable de desechos electrónicos”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre tablas. D-25-3066 Acta 1199/25 del 6/3/25.
264.- Proyecto de ordenanza 264/25: “Aceptar donación de cuadro”. Autor: Intendente Municipal Walter Cortés. Colaboradores: Subsecretaría de Cultura, Diana Garrafa y Departamento Administrativo de la Subsecretaría de Cultura, Micaela Giménez. Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales. O-25-3507 Acta 1205/25 del 12/06/25.
265.- Proyecto de ordenanza 265/25: “Aceptar donación de casetas del correo y un bolso de cartero”. Autor: Intendente Municipal Walter Cortés. Colaboradores: Subsecretaría de Cultura, Diana Garrafa; Coordinador General de la Subsecretaría de Cultura, Gustavo Gaminao y Departamento Administrativo de la Subsecretaría de Cultura, Micaela Giménez. Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales. O-25-3508 Acta 1205/25 del 12/06/25.
266.- Proyecto de declaración 266/25: “Se declara de interés municipal la capacitación Identificación y prevención del suicidio. Autora: Concejala Natalia Almonacid (JSRN). Iniciativa: Red Argentina de Suicidología. Sobre tablas. D-25-3067 Acta 1199/25 del 6/3/25.
267.- Proyecto de comunicación 267/25: “Se comunica a la Subsecretaría de Recursos Forestales - Ministerio de Agricultura, Ganadería y Pesca de la provincia de Río Negro necesidad de exención de derechos de poda/apeo de especies no autóctonas”. Autora: Concejal Samanta Echenique (JxC). Iniciativa: Sra. Susana Calvelo. Sobre tablas. Retirado Acta 1199/25 del 6/3/25.
268.- Proyecto de ordenanza 268/25: “Se autoriza proyecto urbanístico privado y social 19-3-A-A11-10, 19-3-A-395-01, 19-3-A-396-01 y 19-3-A-049-004. Aprueba parámetros urbanísticos. Ordenanza 3443-CM-24”. Autor: Intendente Municipal, Walter Cortés. Colaboradoras. Secretaria Legal y Técnica, Yanina Sánchez y Secretaria de Planeamiento Territorial, Sofia Maggi. Se gira a Asesoría Letrada y a las comisiones de Obras y Planeamiento y de Gobierno y Legales. (Acta 1200/25). 
269.- Proyecto de ordenanza 269/25: “Autoriza proyecto urbanístico privado Brisas del Nahuel 19-3-A-A11-018 y social 19-3-A-049-005. Aprueba parámetros urbanísticos. Ordenanza 3443-CM-24. Autor: Intendente Municipal, Walter Cortés. Colaboradoras. Secretaria Legal y Técnica, Yanina Sánchez y Secretaria de Planeamiento Territorial, Sofia Maggi.  Se gira a Asesoría Letrada y a las comisiones de Obras y Planeamiento y de Gobierno y Legales. (Acta 1200/25). O-25-3517 Acta 1206/25 del 03/07/25.
270.- Proyecto de comunicación 270/25: “Se comunica el rechazo al uso de la resolución 187/25, anexo I de la ANDIS por terminología discriminatoria y contraria a la CDPD”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre tablas. C-25-1157 Acta 1201/25 del 20/03/25.
271.- Proyecto de comunicación 271/25: “Se comunica al Senado de la Nación la necesidad de tratar y aprobar el proyecto S 2453/24”. Autora: Concejala Roxana Ferreyra (Nos Une). Sobre tablas. C-25-1156 Acta 1201/25 del 20/03/25.
272.- Proyecto de ordenanza 272/25: “Se crea el programa 3B Bueno, Barato, Barilochense”. Autora: Concejala Roxana Ferreyra (Nos Une). Se gira a Asesoría Letrada y a las comisiones de Economía, Hacienda, Finanzas y Desarrollo Económico y de Gobierno y Legales.
273.- Proyecto de ordenanza 273/25: “Aceptar donación de computadora”. Autor: Intendente Municipal, Walter Cortés. Colaboradoras: Secretaria Legal y Técnica Yanina Sánchez y Directora General de Comunicación y Gobierno Abierto, Victoria Sofía Najda. Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales. O-25-3509 Acta 1205/25 del 12/06/25.
274.- Proyecto de ordenanza 274/25: “Afecta regalías ordenanza 3349-CM-22: Dispone cierre definitivo CRUM”. Autora: Concejala Julieta Wallace (Incluyendo Bariloche). Colaborador: Dr. Tomás Guevara. Se gira Asesoría Letrada y a las comisiones de Economía, Hacienda, Finanzas y Desarrollo Económico y de Gobierno y Legales. O-25-3501 Acta 1202/25 del 22/05/25.  Vetada por la Resolución 1105-I-25. Acta 1204/25 Veto aceptado.
275.- Proyecto de ordenanza 275/25: “Se instituye Sistema de Áreas Naturales Protegidas (ANP)”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Se gira a Asesoría Letrada y a las comisiones de Turismo y Medio Ambiente y de Gobierno y Legales.
276.- Proyecto de declaración 276/25: “Se declara de interés municipal la tercera edición de la Feria del Libro Local”. Autora: Concejala Natalia Almonacid (JSRN). Iniciativa: Biblioteca Popular Sarmiento. Sobre tablas. D-25-3072 Acta 1201/25 del 20/03/25.
277.- Proyecto de declaración 277/25: “Se declaran de interés municipal los festivales Patagonia Canta”. Autora: Concejala Natalia Almonacid (JSRN). Iniciativa: Sonoro Música. Sobre tablas. D-25-3073 Acta 1201/25 del 20/03/25.
278.- Proyecto de ordenanza 278/25: “Se aprueba presupuesto EMPROTUR 2025. Se incorpora a la ordenanza 3482-CM-24”. Autores: Concejales Gerardo Del Río y Tomás Hercigonja (PUL). Colaboradores: Ente Mixto de Promoción Turística (EMPROTUR). Sobre tablas. O-25-3493 Acta 1201-25 del 20/03/25.
279.- Proyecto de ordenanza 279/25: “Balances Ente Autárquico Administrador y Científico-Técnico del Parque Municipal Llao Llao y Ente Autárquico Mixto Jardín Botánico”. Autor: Presidente del Tribunal de Contralor, Estanislao Cazaux. Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales.
280.- Proyecto de declaración 280/25: “Se declara de interés municipal y comunitario XIX Carrera de Miguel Bariloche”. Autora: Concejala Julieta Wallace (Incluyendo Bariloche). Iniciativa: Comisión Organizadora de la Carrera de Miguel. Sobre tablas. D-25-3074 Acta 1201/25 del 20/03/25
281.- Proyecto de declaración 281/25: “Se declara de interés municipal y científico la trayectoria histórica y el 70° aniversario del Instituto Balseiro”. Autora: Concejala Laura Totonelli (JSRN). Iniciativa: Director Instituto Balseiro, Mariano Cantero. Sobre tablas. D-25-3075 Acta 1201/25 del 20/03/25.
282.- Proyecto de comunicación 282/25: “Comunicar la necesidad del cese inmediato del traslado de la Delegación Cerro Catedral a parcela 19-2-G-144-1B”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre tablas. Retiro Acta 1201/25 del 20/03/25.
283.- Proyecto de ordenanza 283/25: “Aceptación de donación notebook lenovo V15 IAP”. Autor: Intendente Municipal, Walter Cortés. Colaborador: Secretario de Turismo, Sergio Herrero. Se gira a Asesoría Letrada y a la comisión Gobierno y Legales. O-25-3510 Acta 1205/25 del 12/06/25.
284.- Proyecto de declaración 284/25: “Se declara de interés municipal y cultural Diseñoteca Federal Cápsula Bariloche”. Autor: Concejal Juan Pablo Ferrari (JSRN). Iniciativa: Organizadoras y anfitrionas, Ada Cintia Schiavo, Jésica Beaudean y Jazmín Fernández Murgic “Bariloche NOT Moda”. Se solicitará su retiro por haberse emitido la resolución 157-PCM-25. D-25-3096 Acta 1202/25 del 22/05/25.
285.- Proyecto de declaración 285/25: “Se declara de interés municipal y cultural al evento Danzarium en Bariloche 2025”. Autor: Presidente del Concejo Municipal, Gerardo Del Río. Iniciativa: Directora ensamble danza Bariloche, Mónica Vega. Se solicitará su retiro por haberse emitido la resolución 167-PCM-25. D-25-3098 Acta 1202/25 del 22/05/25.
286.- Proyecto de declaración 286/25: “Se declara de interés municipal disciplinas de freestyle en ski y snowboard como actividad de relevancia deportiva, formativa y turística”. Autor: Concejal Juan Pablo Ferrari (JSRN). Iniciativa: Federación Argentina de Ski y Andinismo (FASA). Sobre tablas. D-25-3082 Acta 1202/25 del 22/05/25.
287.- Proyecto de comunicación 287/25: “Se comunica repudio a los dichos de Javier Milei sobre la soberanía en las islas Malvinas”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre tablas. C-25-1158 Acta 1202/25 del 22/05/25.
288.- Proyecto de declaración 288/25: “Se declara de interés municipal al 40° aniversario de la Escuela Municipal de Arte La Llave”. Autor: Concejal Gerardo Del Río (PUL). Iniciativa: Directora de formación artística de la Escuela Municipal de Arte La Llave, Ana Pereda. Sobre tablas. D-25-3083 Acta 1202/25 del 22/05/25.
289.- Proyecto de declaración 289/25: “Se declara de interés municipal y comunitario formación profesional en Danzaterapia 2025”. Autora: Concejala Roxana Ferreyra (Nos Une). Iniciativa: Sonia López. Se solicitará su retiro por haberse emitido la resolución 183-PCM-25. D-25-3099 Acta 1202/25 del 22/05/25.
290.- Proyecto de declaración 290/25: “Se declara de interés municipal, comunitario y social a la Piedra de la Memoria” Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Se solicitará su retiro por haberse emitido la resolución 199-PCM-25. D-25-3102 Acta 1202/25 del 22/05/25.
291.- Proyecto de comunicación 291/25: “Se comunica a instituciones necesidad de cumplir ley J 4395 (Suspensión Corte Servicios)” Autores: Concejales Julieta Wallace, Leandro Costa Butten (Incluyendo Bariloche), Roxana Ferreyra (Nos Une), Facundo Villalba (Primero Río Negro), Samanta Echenique (JxC), Laura Totonelli y Juan Pablo Ferrari (JSRN). Sobre tablas. C-25-1159 Acta 1202/25 del 22/05/25.
292.- Proyecto de ordenanza 292/25: “Reglamentación del inciso 19 del artículo 38° de la COM”. Autora: Concejal Samanta Echenique (JxC). Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales. O-25-3518 Acta 1206/25 del 03/07/25.
293.- Proyecto de declaración 293/25: “Se declara de interés municipal a la participación de Brisas Andinas en el Festival Internacional Fucare 2025”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre tablas. D-25-3084 Acta 1202/25 del 22/05/25.
294.- Proyecto de declaración 294/25: “Se declara de interés municipal el proyecto Guardián de hierro del Nahuel Huapi”. Autora: Concejala Natalia Almonacid (JSRN). Iniciativa: Walter Jung. Sobre tablas. D-25-3085 Acta 1202/25 del 22/05/25.
295.- Proyecto de declaración 295/25: “Se declara de interés municipal el proyecto del documental El vacío entre manzanas”. Autora: Concejala Natalia Almonacid (JSRN). Iniciativa: Damián Leibovich. Sobre tablas. D-25-3086 Acta 1202/25 del 22/05/25.
296.- Proyecto de declaración 296/25: “Se declara de interés municipal el Memorial Museo Malvinas Antártida y Atlántico Sur”. Autores: Concejales Natalia Almonacid, Laura Totonelli y Juan Pablo Ferrari (JSRN). Iniciativa: Dirección Provincial de Veteranos de Guerra de Río Negro. Sobre tablas. D-25-3079 Acta 1202/25 del 22/05/25.
297.- Proyecto de ordenanza 297/25: “Se declara ciudadano ilustre de Bariloche al veterano ex combatiente de Malvinas Pablo Marcos Rafael Carballo”. Autores: Concejales Natalia Almonacid, Laura Totonelli y Juan Pablo Ferrari (JSRN). Iniciativa: Dirección Provincial de Veteranos de Guerra de Río Negro. Sobre tablas. O-25-3502 Acta 1202/25 del 22/05/25.

298.- Proyecto de declaración 298/25: “Se declara de interés municipal el Tercer Encuentro de Matemática RSME-UMA”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Iniciativa: Departamento de Matemática, UNCo Bariloche. Sobre tablas. D-25-3087 Acta 1202/25 del 22/05/25.
299.- Proyecto de ordenanza 299/25: “Se crea programa municipal Esquí y Montaña Escolar”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Se gira a Asesoría Letrada y a las comisiones de Economía, Hacienda, Finanzas y Desarrollo Económico y de Gobierno y Legales.
300.- Proyecto de declaración 300/25: “Se declara de interés municipal y comunitario Festival y Campeonato de Tango Si querés bailar, bailá. Autora: Concejala Roxana Ferreyra (Nos Une). Iniciativa: Patricia Gallo y Natalí Claveríz. Se solicitará su retiro por haberse emitido la resolución 236-PCM-25. D-25-3104 Acta 1202/25 del 22/05/25.
301.- Proyecto de ordenanza 301/25: “Se modifica ordenanza 1747-CM-07”. Autora: Concejala Natalia Almonacid (JSRN). Iniciativa: Junta vecinal Calfu Ruca 150 Viviendas. Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales. O-25-3511 Acta 1205/25 del 12/06/25.
302.- Proyecto de ordenanza 302/25: “Autoriza suscribir convenio de comodato para la empresa Coopetel. Parcela N.C: 19-2-N-N10-04”. Autor: Intendente Municipal, Walter Cortés. Colaboradores: Secretaria de Planeamiento Territorial, Sofia Maggi e Instituto Municipal de Tierras y Viviendas para el Hábitat Social. Se gira a Asesoría Letrada y a las comisiones de Obras y Planeamiento y de Gobierno y Legales.
303.- Proyecto de ordenanza 303/25: “Se crea la Mesa de Ciencia y Tecnología para la Comunidad (MCTC)”. Autores: Concejales Laura Totonelli, Natalia Almonacid y Juan Pablo Ferrari (JSRN). Colaboradores: Sebastián Iván Benítez (UTN) y Marcelo Alonso (UNCOMA). Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales.
304.- Proyecto de declaración 304/25: “Se declara de interés municipal y comunitario el festejo del 27° aniversario del barrio Unión”. Autora: Concejala Roxana Ferreyra (Nos Une). Iniciativa: Junta vecinal barrio Unión. Se solicitará su retiro por haberse emitido la resolución 198-PCM-25. D-25-3101 Acta 1202/25 del 22/05/25.
305.- Proyecto de ordenanza 305/25: “Se adhiere al Día Internacional de la Epilepsia. Modifica ordenanza 2033-CM-10”. Autor: Concejal Facundo Blanco Villalba (Primero Río Negro). Colaboradora: Daniela Pacheco (Púrpura Bariloche). Sobre tablas. O-25-3503 Acta 1202/25 del 22/05/25.
306.- Proyecto de declaración 306/25: “Se declara de interés municipal la 2° edición de La Semana de los Jardines de Infantes”. Autores: Concejales Gerardo Del Río, Tomás Hercigonja y María del Carmen Coronado (PUL). Iniciativa: Instituto de Formación Docente Continua Bariloche. Sobre tablas. D-25-3088 Acta 1202/25 del 22/05/25.
307.- Proyecto de ordenanza 307/25: “Adherir al decreto provincial 2024-380-EGDERNE-RNE. Reconocimiento a soldados continentales. Autores: Concejales Gerardo Del Río, Tomás Hercigonja y María Coronado (PUL). Sobre tablas. O-25-3504 Acta 1202/25 del 22/05/25.

308.- Proyecto de declaración 308/25: “Se declara de interés municipal y cultural el Festival Arte X Igual”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Se solicitará su retiro por haber sido aprobada la declaración 3078-CM-25. Retirado Acta 1202/25 del 22/05/25.
309.- Proyecto de declaración 309/25: “Se declara de interés municipal y cultural la trayectoria de la banda El Alambique”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre tablas. D-25-3089 Acta 1202/25 del 22/05/25.
310.- Proyecto de declaración 310/25: “Declarar de interés municipal a la mediación comunitaria en la Defensoría del Pueblo”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Colaboradora: Andrea Galaverna. Sobre tablas. D-25-3090 Acta 1202/25 del 22/05/25.
311.- Proyecto de resolución 311/25: “Se modifica el punto 29, Título III del Anexo II de la resolución 697-CM-23”. Autores: Concejales Gerardo Del Río, María del Carmen Coronado, Tomás Hercigonja (PUL), Juan Pablo Ferrari, Laura Totonelli (JSRN), Leandro Costa Brutten, Julieta Wallace (Incluyendo Bariloche), Samanta Echenique (JxC) y Roxana Ferreyra (Nos Une). Sobre tablas. R-25-743 Acta 1202/25 del 22/05/25.
312.- Proyecto de resolución 312/25: “Se notifica no conformidad con resolución 586-I-25”. Autores: Concejales Julieta Wallace, Leandro Costa Brutten (Incluyendo Bariloche), Roxana Ferreyra (Nos Une) y Facundo Blanco Villalba (Primero Río Negro). Sobre tablas. R-25-744 Acta 1202/25 del 22/05/25.
313.- Proyecto de ordenanza 313/25: “Se abroga resolución de intendencia 586-I-25”. Concejales: Julieta Wallace y Leandro Costa Brutten (Incluyendo Bariloche); Roxana Ferreyra (Nos Une) y Facundo Blanco Villalba (Primero Río Negro). Sobre tablas. O-25-3505 Acta 1202/25 del 22/05/25.  Vetada por la Resolución 1053-I-25. Acta 1204/25 Veto aceptado.
314.- Proyecto de comunicación 314/25: “Se comunica repudio a la disolución del Fondo de Integración Socio Urbana”. Autores: Concejales Leandro Costa Brutten, Julieta Wallace (Incluyendo Bariloche) y Roxana Ferreyra (Nos Une). Iniciativa: Mesa de Barrios Populares. Sobre tablas. C-25-1160 Acta 1202/25 de 22/05/25.
315.- Proyecto de comunicación 315/25: “Se comunica al Ejecutivo municipal dé pleno cumplimiento a la ordenanza 716-CM-97”. Autora: Concejala Roxana Ferreyra (Nos Une). Sobre tablas. C-25-1161 Acta 1202/25 del 22/05/25.
316.- Proyecto de comunicación 316/25: “Se comunica al Ejecutivo municipal dé pleno cumplimiento a la ordenanza 2983-CM-18”. Autora: Concejala Roxana Ferreyra (Nos Une). Sobre tablas. C-25-1162 Acta 1202/25 del 22/05/25.
317.- Proyecto de declaración 317/25: “Declarar de interés municipal los 30 años de trayectoria del CRIP”. Autora: Concejala Natalia Almonacid (JSRN). Sobre tablas. D-25-3080 Acta 1202/25 del 22/05/25.
318.- Proyecto de ordenanza 318/25: “Se modifica ordenanza 137-C-88”. Autor: Intendente Municipal, Walter Cortés. Colaboradores: Vicejefe de Gabinete, Carlos Iglesias y Secretaria Legal y Técnica, Yanina Andrea Sánchez. Sobre tablas. Rechazado Acta 1202/25 del 22/05/25.
319.- Proyecto de declaración 319/25: “Se declara de interés municipal el XLV Congreso Nacional e Internacional de Folclore”. Autora: Concejala Natalia Almonacid (JSRN). Sobre tablas. D-25-3081 Acta 1202/25 del 22/05/25.
320.- Proyecto de declaración 320/25: “Se declara de interés municipal y cultural 5° Encuentro de Cantoras”. Autora: Concejala Julieta Wallace (Incluyendo Bariloche). Iniciativa: Cantoras de Aquí y de Allá- Las Comadras. Sobre tablas. D-25-3091 Acta 1202/25 del 22/05/25.
321.- Proyecto de comunicación 321/25: “Se comunica respaldo a la lucha del sector científico ante el desfinanciamiento nacional”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre tablas. C-25-1163 Acta 1205/25 del 12/06/25.
322.- Proyecto de comunicación 322/25: “Se comunica repudio al DNU 340/25 del Poder Ejecutivo Nacional”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre tablas. C-25-1164 Acta 1205/25 del 12/06/25.
323.- Proyecto de comunicación 323/25: “Se solicita al Poder Ejecutivo Nacional el cese de los ataques contra la libertad de prensa”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre tablas. C-25-1165 Acta 1205/25 del 12/06/25.
324.- Proyecto de comunicación 324/25: “Se comunica el rechazo al recorte de subsidios a usuarios de régimen de zona fría”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre tablas. C-25-1166 Acta 1205/25 del 12/06/25.
325.- Proyecto de ordenanza 325/25: “Aceptar donación de un decibelímetro”. Autor: Intendente Municipal, Walter Cortés. Colaboradores: Secretaria Legal y Técnica, Yanina Sánchez, Secretario de Protección Ciudadana, Carlos Madjinca y Subsecretario de Inspección General, Nelson Fabián Llacer. Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales.
326.- Proyecto de ordenanza 326/25: “Establece jornadas municipales de concientización vial. Modifica ordenanza 2033-CM-10”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Iniciativa: Mesa 6 de Septiembre. Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales. O-25-3519 Acta 1206/25 del 03/07/25.
327.- Proyecto de declaración 327/25: “Se declara de interés municipal y comunitario Mesa de Trabajo Participativa para el Diseño de Iniciativas Estatales sobre Personas en Situación de Calle”. Autora: Concejala Roxana Ferreyra (Nos Une). Iniciativa: Mesa de Trabajo Participativa para el Diseño de Iniciativas Estatales sobre Personas en Situación de Calle. Sobre tablas. D-25-3105 Acta 1205/25 del 12/06/25.
328.- Proyecto de ordenanza 328/25: “Se modifica ordenanza 3080-CM-19”. Autora: Concejala Roxana Ferreyra (Nos Une). Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales.  (con Prioridad de dictamen Com. Leg del 11/6/25 Acta 53/25). O-25-3520 Acta 1206/25 del 03/07/25.
329.- Proyecto de declaración 329/25: “Declara de interés municipal y cultural el libro Plantas Nativas de la Patagonia”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre tablas. D-25-3106 Acta 1205/25 del 12/06/25.
330.- Proyecto de declaración 330/25: “Se declara de interés municipal y cultural el libro Flores de la Patagonia”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre tablas. D-25-3107 Acta 1205/25 del 12/06/25.
331.- Proyecto de ordenanza 331/25: “Se adhiere a la Red Federal de Turismo”. Autor: Concejal Juan Pablo Ferrari (JSRN). Iniciativa: Emprotur. Colaboradora: Abogada Natacha Vázquez. Sobre tablas. O-25-3512 Acta 1205/25 del 12/06/25.
332.- Proyecto de ordenanza 332/25: “Se adhiere a la ley nacional 27671 cuestión de las Islas Malvinas. Establécese capacitación obligatoria, periódica y permanente”. Autora Concejala Roxana Ferreyra (Nos Une). Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales.
333.- Proyecto de ordenanza 333/25: “Se crea Registro Municipal de Consultores Ambientales”. Autores: Concejales Laura Totonelli y Juan Pablo Ferrari (JSRN). Iniciativa: Colegio de Arquitectos de Río Negro y Consejo Profesional de Ingenieros y Técnicos de la arquitectura e ingeniería de Río Negro. Se gira a Asesoría Letrada y a las comisiones de Turismo y Medio Ambiente y de Gobierno y Legales.
334.- Proyecto de ordenanza 334/25: “Suspensión de la exigencia de la RTO en el ejido Municipal”. Autor: Concejal Facundo Blanco Villalba (Primero Río Negro). Se gira a Asesoría Letrada y a las comisiones de Servicios, Tránsito y Transporte y de Gobierno y Legales.
335.- Proyecto de declaración 335/25: “Se declara de interés municipal y cultural la muestra Programa de Conservación Cóndor Andino”. Autor: Concejal Juan Pablo Ferrari (JSRN). Iniciativa: Grupo de fotógrafos y artistas del Programa de Conservación Cóndor. Sobre tablas. D-25-3108 Acta 1205/25 del 12/06/25.
336.- Proyecto de ordenanza 336/24: “Se regula prestación del servicio de transporte de pasajeros mediante vehículos y conductores que operan a través de plataformas digitales”. Autora: Concejala Roxana Ferreyra (Nos Une). Se gira a Asesoría Letrada y a las comisiones de Economía, Hacienda, Finanzas y Desarrollo Económico; de Servicios Tránsito y Transporte y de Gobierno y Legales. (con Prioridad de dictamen Com. Leg del 11/6/25 Acta 53/25).
337.- Proyecto de declaración 337/25: “Se declara de interés municipal el XVI Tedeum Evangélico”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre tablas. D-25-3110 Acta 1206/25 del 03/07/25.
338.- Proyecto de comunicación 338/25: “Se solicita la reconsideración de las restricciones al ingreso de transporte turístico al Cerro Tronador”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre tablas. C-25-1167 Acta 1206/25 del 03/07/25.
339.- Proyecto de comunicación 339/25: “Se solicita que se respeten las garantías procesales y se sostengan las presentaciones ante organismos internacionales de derechos humanos”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre tablas. Rechazada Acta 1206/25 del 03/07/25.
340.- Proyecto de declaración 340/25: “Se declara de interés municipal y comunitario la trayectoria del Club Social y Deportivo Llao Llao”. Autora: Concejala Roxana Ferreyra (Nos Une). Iniciativa: Club Social y Deportivo Llao Llao. Sobre tablas. D-25-3111 Acta 1206/25 del 03/07/25.
341.- Proyecto de ordenanza 341/25: “Se reglamenta referéndum popular”. Autores: Concejales Laura Totonelli, Natalia Almonacid y Juan Pablo Ferrari (JSRN). Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales.
342.- Proyecto de declaración 342/25: “Se declara de interés municipal la película La suspensión del tiempo”. Autora: Concejala Laura Totonelli (JSRN). Iniciativa: Comisión Fílmica Bariloche. Sobre tablas. D-25-3112 Acta 1206/25 del 03/07/25.
343.- Proyecto de comunicación 343/25: “Se comunica repudio al decreto 383/2025”. Autora: Concejala Julieta Wallace (Incluyendo Bariloche). Iniciativa: Juventud Peronista Bariloche. Sobre tablas. C-25-1168 Acta 1206/25 del 03/07/25.
344.- Proyecto de comunicación 344/25: “Se comunica repudio al decreto 345/2025”. Autora: Concejala Julieta Wallace (Incluyendo Bariloche). Iniciativa: Asociación Civil Teatrantes Bariloche. Sobre tablas. C-25-1169 Acta 1206/25 del 03/07/25.
345.- Proyecto de comunicación 345/25: “Se comunica al Poder Ejecutivo Municipal necesidad inmediata remoción vehículos secuestrados-incautados”. Autora: Concejala Laura Totonelli (JSRN). Sobre tablas. C-25-1170 Acta 1206/25 del 03/07/25.
346.- Proyecto de ordenanza 346/25: “Modifica anexo I ordenanza 1747-CM-07. Se asigna nombre calles barrio El Cóndor I”. Autor: Concejal Gerardo Del Río (PUL). Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales.
347.- Proyecto de ordenanza 347/25: “Se crea comisión especial investigadora de la concesión del Cerro Catedral”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales.
348.- Proyecto de ordenanza 348/25: “Se establece semana de visibilización de los derechos de las personas en situación de calle. Se modifica ordenanza 2033-CM-10”. Autora: Concejala Roxana Ferreyra (Nos Une). Iniciativa: Mesa de trabajo participativa para el diseño de iniciativas estatales sobre la problemática de personas en situación de calle. Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales.
349.- Proyecto de resolución 349/25: “Se expresa repudio a proscripción política de Cristina Fernández de Kirchner”. Autora: Concejala Roxana Ferreyra (Nos Une). Sobre tablas. C-25-1171 Acta 1206/25 del 03/07/25.

350.- Proyecto de ordenanza 350/25: “Se crea la comisión especial Martina Linares”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales.
351.- Proyecto de comunicación 351/25: “Se repudia el cierre de sucursales del Banco Nación y se solicita la revisión de esta medida”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Sobre tablas. C-25-1172 Acta 1206/25 del 03/07/25.
352.- Proyecto de declaración 352/25: “Se declara de interés municipal la revista del C.E.N.S. 9 La Nocturna”. Autora: Concejala Natalia Almonacid (JSRN). Sobre tablas. D-25-3113 Acta 1206/25 del 03/07/25.
353.- Proyecto de declaración 353/25: “Se declara de interés municipal la Reunión Nacional de Química organizada por UNRN-ADEQRA”. Autor: Concejal Leandro Costa Brutten (Incluyendo Bariloche). Iniciativa: Dra. Andrea S. Farré, Comité organizador XXI Reunión de Educadores en la Química. Sobre tablas. D-25-3114 Acta 1206/25 del 03/07/25.
354.- Proyecto de ordenanza 354/25: “Se reconoce junta vecinal 136 Viviendas, personería jurídica y delimita jurisdicción. Modifica ordenanza 2546-CM-14”. Autora: Concejala Natalia Almonacid (JSRN). Iniciativa: Comisión promotora de trabajo vecinal barrio 136 viviendas. Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales.
355.- Proyecto de ordenanza 355/25: “Se ratifica convenio subsidio TUP 2025”. Autor: Intendente Municipal Walter Cortés. Colaboradores: Secretaria Legal y Técnica, Yanina Sanchéz y Secretaria de Hacienda, Carina Ondarcuhu. Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales.
356.- Proyecto de ordenanza 356/25: “Ratifica convenios y amplía Presupuesto 2025”. Autor: Intendente Municipal Walter Cortés. Colaboradores: Secretaria Legal y Técnica, Yanina Sanchéz; Secretaria de Hacienda, Carina Ondarcuhu y Secretaría de Obras y Planeamiento Urbano; Secretaría de Obras y Servicios Públicos. Se gira a Asesoría Letrada y a las comisiones de Economía, Hacienda, Finanzas y Desarrollo Económico y de Gobierno y Legales.
357.- Proyecto de ordenanza 357/25: “Creación organigrama político, determinación de misiones y funciones”. Autor: Intendente Municipal Walter Cortés. Colaboradora: Secretaria Legal y Técnica, Yanina Sanchéz. Se gira a Asesoría Letrada y a la comisión de Gobierno y Legales. 
358.- Proyecto de declaración 358/25: “Se declara de interés municipal al Circuito de Turismo Científico, Educativo y Tecnológico”. Autora: Concejala Laura Totonelli (JSRN). Iniciativa: Diego Libkind, Director de IPATEC (Instituto Andino Patagónico de Tecnología Biológicas). Sobre tablas. D-25-3115 Acta 1206/25 del 03/07/25.
359.- Proyecto de ordenanza 359/25: “Se modifica anexo I de la ordenanza tarifaria 2375-CM-12”. Autor: Concejal Facundo Villalba (Primero Río Negro). Sobre tablas. O-25-3521 Acta 1206/25 del 03/07/25.



`;

// Procesar proyectos
const proyectos = parsearProyectos(proyectosTexto);

// Guardar en archivo JSON
const fs = require('fs');
fs.writeFileSync('proyects.json', JSON.stringify(proyectos, null, 2));

console.log(`Procesados ${proyectos.length} proyectos. Guardados en proyectos.json`);